import { Roll } from "../../../shared/types"

export const HEIGHT_CHART: readonly Roll[] = [
  [78, `giraffe-like`],
  [77, `extremely tall`],
  [76, `very tall`],
  [75, `rather tall`],
  [74, `quite tall`],
  [73, `reasonably tall`],
  [72, `tall`],
  [71, `taller than average`],
  [70, `average sized`],
  [69, `medium sized`],
  [68, `on the short side`],
  [67, `somewhat short`],
  [66, `relatively short`],
  [65, `short-ish`],
  [64, `short`],
  [63, `short`],
  [62, `rather short`],
  [61, `barely five foot`],
  [60, `quite short`],
  [59, `rather small`],
  [58, `really short`],
  [57, `pint sized`],
  [56, `quite small`],
  [55, `small`],
  [54, `squat`],
  [53, `somewhat squat`],
  [52, `quite squat`],
  [50, `rather squat`],
  [48, `somewhat tiny`],
  [46, `rather small`],
  [44, `rather tall (compared to a halfling)`],
  [42, `tall (for a halfling)`],
  [40, `barely a metre`],
  [38, `diminuitive`],
  [36, `quite diminuitive`],
  [34, `adorably short`],
  [32, `tiny`],
  [30, `so so tiny`],
  [0, `impossibly small`],
]
