import { dice, randomRange } from "../rolls"
import { dwarfTraits } from "./race-traits/dwarf"
import { dragonbornTraits } from "./race-traits/dragonborn"
import { elfTraits } from "./race-traits/elf"
import { gnomeTraits } from "./race-traits/gnome"
import { halfElfTraits } from "./race-traits/half-elf"
import { halflingTraits } from "./race-traits/halfling"
import { halfOrcTraits } from "./race-traits/half-orc"
import { humanTraits } from "./race-traits/human"
import { tieflingTraits } from "./race-traits/tiefling"
import { RaceTrait } from "./race-traits/race-trait"
import { NPC } from "./npc"
import { MajorRace } from "../../../shared/Race"
import { genderData } from "./genderData"

export function pronouns(npc: NPC) {
  return genderData[npc.gender]
}

export const npcData: any = {
  gender: genderData,
  doesnt: {
    "wants to grow a beard": {
      probability: 5,
      exclusions(town: any, npc: any) {
        return npc.beard || (npc.gender !== `man` && randomRange(0, 100) <= npc.beardProbability)
      },
      function(town: any, npc: any) {
        return `${npc.name} doesn't say ${npc.heshe} wants to grow a beard.`
      },
    },
    "no longer loves partner": {
      probability: 5,
      exclusions(town: any, npc: any) {
        if (!npc.partnerID) {
          return false
        } else {
          return true
        }
      },
      function(town: any, npc: any) {
        return `${npc.name} doesn't say ${npc.heshe} no longer loves ${npc.hisher} ${
          npc.partnerID.marriageNoun
        }, <<profile $npcs[${JSON.stringify(npc.partnerID)}]>>`
      },
    },
    "has a sizeable inheritance": {
      probability: 5,
      exclusions(town: any, npc: any) {
        return true
      },
      function(town: any, npc: any) {
        npc.wealth += 50000
        return `${npc.name} doesn't say ${npc.heshe} has a sizeable inheritance.`
      },
    },
    "wants to run away": {
      probability: 5,
      // type: ['says', 'doesnt', 'hides'],
      exclusions(town: any, npc: any) {
        if (npc.background !== `hermit`) {
          return true
        }
      },
      function(town: any, npc: any) {
        return `${npc.name} doesn't say ${npc.heshe} wants to run away and live far away from society.`
      },
    },
  },

  skinColour: [
    `translucent`,
    `white`,
    `pale`,
    `fair`,
    `light`,
    `light tan`,
    `tan`,
    `pale`,
    `fair`,
    `light`,
    `light tan`,
    `tan`,
    `dark tan`,
    `brown`,
  ],
  profession: [
    `actor`,
    `advocate`,
    `advisor`,
    `animal handler`,
    `apothecary`,
    `architect`,
    `archivist`,
    `armorer`,
    `astrologer`,
    `baker`,
    `banker`,
    `barber`,
    `barkeep`,
    `blacksmith`,
    `bookseller`,
    `brewer`,
    `bricklayer`,
    `brothel keeper`,
    `buccaneer`,
    `butcher`,
    `caravanner`,
    `carpenter`,
    `cartographer`,
    `chandler`,
    `chef`,
    `clock maker`,
    `cobbler`,
    `cook`,
    `counselor`,
    `courtesan`,
    `courtier`,
    `cowherd`,
    `dancer`,
    `diplomat`,
    `distiller`,
    `diver`,
    `farmer`,
    `fisherman`,
    `fishmonger`,
    `gardener`,
    `general`,
    `gladiator`,
    `glovemaker`,
    `goldsmith`,
    `grocer`,
    `guardsman`,
    `guildmaster`,
    `hatmaker`,
    `healer`,
    `herald`,
    `herbalist`,
    `hermit`,
    `historian`,
    `hunter`,
    `ice seller`,
    `innkeeper`,
    `inventor`,
    `jailer`,
    `jester`,
    `jeweler`,
    `judge`,
    `knight`,
    `lady`,
    `leatherworker`,
    `librarian`,
    `linguist`,
    `locksmith`,
    `lord`,
    `lumberjack`,
    `mason`,
    `masseur`,
    `merchant`,
    `messenger`,
    `midwife`,
    `miller`,
    `miner`,
    `minister`,
    `minstrel`,
    `monk`,
    `mortician`,
    `necromancer`,
    `noble`,
    `nun`,
    `nurse`,
    `officer`,
    `painter`,
    `patissier`,
    `perfumer`,
    `philosopher`,
    `physician`,
    `pilgrim`,
    `potter`,
    `priest`,
    `privateer`,
    `professor`,
    `roofer`,
    `ropemaker`,
    `rugmaker`,
    `saddler`,
    `sailor`,
    `scabbard maker`,
    `sculptor`,
    `scavenger`,
    `scholar`,
    `seamstress`,
    `servant`,
    `shaman`,
    `shepherd`,
    `ship's captain`,
    `silversmith`,
    `slave`,
    `slaver`,
    `smith`,
    `soldier`,
    `spice merchant`,
    `squire`,
    `stablehand`,
    `stevedore`,
    `stonemason`,
    `steward`,
    `street seller`,
    `street sweeper`,
    `student`,
    `surgeon`,
    `surveyor`,
    `sailor`,
    `tanner`,
    `tavernkeeper`,
    `tax collector`,
    `teacher`,
    `thatcher`,
    `thief`,
    `torturer`,
    `town crier`,
    `toymaker`,
    `vendor`,
    `veterinarian`,
    `vintner`,
    `weaver`,
    `wetnurse`,
    `woodcarver`,
    `wood seller`,
    `wrestler`,
    `writer`,
  ],
  trait: [
    `fidgets`,
    `drinks too much`,
    `eats too much`,
    `swears often`,
    `has poor hygiene`,
    `cannot resist flirting`,
    `cannot stop staring at you`,
    `sweats profusely and easily`,
    `is a habitual liar`,
    `embellishes the truth`,
    `exaggerates details`,
    `has a short temper`,
    `is melodramatic`,
    `gossips about the most mundane things`,
    `cannot resist a juicy secret`,
    `chews with an open mouth`,
    `often sniffs audibly`,
    `is incredibly gullible`,
    `is skeptical of everything`,
    `paces about incessantly`,
    `makes poor eye contact`,
    `is a know it all`,
    `corrects people's grammar when they speak`,
    `blinks constantly`,
    `bobs head back and forth when speaking`,
    `is often sarcastic`,
    `cannot resist making snide comments`,
    `loses train of thought easily`,
    `is always shaking`,
  ],
  idle: [
    `sitting, with a piece of bread in hand`,
    `sitting, mug in hand`,
    `poring over some map`,
    `reading some letter intently`,
    `reading a book`,
    `shuffling a pack of cards`,
    `chewing on a piece of hay`,
    `sharpening a knife`,
    `buffing a piece of armour`,
    `polishing a shield`,
    `sharpening the blade on a fearsome looking dagger`,
    `cutting an apple into bite sized pieces`,
    `biting into an apple`,
    `eating an apple while looking at some book`,
    `eating a hunk of cheese while reading a book`,
    `sipping out of a huge mug while reading a book`,
    `reading a book titled '<<print $book.pun.pluck()>>'`,
    `reading a book titled '<<print $book.pun.pluck()>>'`,
    `reading a book titled '<<print $book.pun.pluck()>>'`,
  ],
  reading: [
    `a piece of history- my forefather's journal, detailing his life in $town.name when it was just a settlement.`,
    `my journal, from many years ago.`,
    `my mother's journal, from just before she disappeared`,
    `a document which I received by postboy two days ago... I believe it is in code, and somebody is trying to tell me something.`,
    `a traitor's memoirs, extremely rare... I thought it would be a good laugh, but some of what he says is concerningly accurate.`,
    `some sort of spell, though I don't know how to read it.`,
    `a document I bought at the flea market; it looks to be a set of instructions on how to make a golem.`,
    `a book which I bought, believing it to be blank, and suitable for a journal. However, now there's this strange foreign script that I can't read in it.`,
    `a book that I bought as a gift for my mother, who loves beautiful covers, despite not being able to read.`,
  ],
  currentMood: [
    `annoyed`,
    `scared`,
    `relaxed`,
    `concerned`,
    `bemused`,
    `stressed`,
    `amused`,
    `content`,
    `distracted`,
    `discontent`,
  ],
  scar: [
    `a jagged scar`,
    `a dark purple scar`,
    `an angry red scar`,
    `a long, thin scar running up the arm`,
    `a scar on the eye`,
    `a scar around the neck`,
    `a scar on the throat`,
    `a fiery red scar`,
    `a finger missing`,
    `two fingers missing`,
    `a chunk of left ear missing`,
    `a chunk of right ear missing`,
    `a scar through the eyebrow`,
    `a scar across the cheek`,
    `a scar on the nose`,
    `a scar down the forehead`,
    `a scar in the middle of the hand`,
    `a crooked scar along the jaw`,
  ],
  tattoo: [
    `a dagger tattoo`,
    `an arrow tattoo`,
    `an anchor tattoo`,
    `a skull tattoo`,
    `a pair of crossed bones tattoo`,
    `a snake tattoo`,
    `a scorpion tattoo`,
    `a spider web tattoo`,
    `a heart tattoo`,
    `a ring of thorns tattoo`,
    `a mermaid tattoo`,
    `a dragon tattoo`,
  ],
  demeanour: [`calm`, `moody`, `kind`, `conceited`, `cruel`, `mean`, `careful`, `polite`, `happy`],
  vocalPattern: [
    `is incoherent except for a few key words`,
    `stutters`,
    `says ‘um’ a lot`,
    `says ‘like’ a lot`,
    `swears`,
    `uses thee's and thou's`,
    `never stops to breathe`,
    `uses short, clipped sentences`,
    `talks in third person`,
    `doesn't conjugate well (‘me make good soup’)`,
    `rolls R’s`,
    `never uses contractions`,
    `is whiny`,
    `obviously has a stuffy nose`,
    `tongue stuck to back of teeth`,
    `does so through clenched teeth`,
    `speaks in a sing-song voice`,
    `likes to rhyme`,
    `spits on every 's' sound`,
    `makes all Th-sounds become Z-sounds`,
    `repeats the last few words of a sentence/thought (‘nice to meet you, meet you’)`,
    `uses full titles or descriptions of how he knows you (‘ellen-farmers-daughter is pretty’)`,
    `strings together adjectives/adverbs for more impact (‘wow, your dress is pretty-pretty!’ ‘I am short-short-short.’)`,
    `all non-proper nouns end with ‘en’/’sen’ (‘may I have some applesen?’ ‘I saw a big moosen!’)`,
    `all L-sounds become w-sounds`,
    `repeats the last word you say before responding`,
    `sings everything`,
    `does the wrong emphasis on the wrong syllables`,
    `pauses often`,
    `has a clipped pattern of speech`,
    `is rather monotonous`,
    `whistles on S-sounds`,
    `spits on Th-sounds and S-sounds (think Sylvester the cat from Looney toons)`,
    `has a light lisp`,
    `makes all r-sounds become w-sounds`,
    `has a severe underbite`,
    `has a severe overbite`,
    `speaks out of the corner of his mouth`,
    `is always pouting`,
    `makes ‘ar/er’ sounds become ‘aye’ sounds (fart will sound like fight, water will sound like watay)`,
    `makes soft letters elongated (‘ssssso, hhhhhhow are you?’)`,
    `slurs words`,
    `always has a full mouth while talking`,
    `sighs after each sentence`,
    `never uses am/is/are/was/were (‘I big.’ ‘She pretty.’)}`,
    `responds in the form of questions`,
    `mutters`,
  ],
  calmTrait: [
    `compassionate`,
    `cheerful`,
    `reserved`,
    `outspoken`,
    `uninterested`,
    `gruff`,
    `eager`,
    `deceitful`,
    `foolish`,
    `strict`,
    `agreeable`,
    `mischeivious`,
    `angry`,
    `fearful`,
    `manipulative`,
    `devout`,
    `greedy`,
    `funny`,
    `dour`,
    `fun-loving`,
    `lazy`,
    `driven`,
    `boastful`,
    `artistic`,
    `assertive`,
    `carefree`,
    `cautious`,
    `confident`,
    `thoughtful`,
    `loyal`,
    `sophisticated`,
    `weak-willed`,
  ],
  stressTrait: [
    `withdrawn`,
    `murderous`,
    `obsessive`,
    `authoritarian`,
    `determined`,
    `brave`,
    `spiteful`,
    `belligerent`,
    `caustic`,
    `reckless`,
    `argumentative`,
    `gluttonous`,
    `overly protective`,
    `angry`,
    `cowardly`,
    `meticulous`,
    `sarcastic`,
    `stubborn`,
    `destructive`,
    `practical`,
    `pushy`,
    `fanatical`,
    `secretive`,
    `scornful`,
    `courageous`,
    `impractical`,
    `calculating`,
    `industrious`,
    `manipulative`,
    `destructive`,
    `compulsive`,
    `intolerant`,
  ],
  adventure: [
    `retired from adventuring`,
    `currently looking for an adventure`,
    `looking for assistance`,
    `recuperating from an adventure`,
    `on a holiday from adventuring`,
    `taking a short break from adventuring`,
  ],
  hairColour: [
    `brunette`,
    `brunette`,
    `brown`,
    `brownish`,
    `auburn`,
    `amber`,
    `hazel`,
    `red`,
    `dark red`,
    `blonde`,
    `dark blonde`,
    `white`,
    `platinum`,
    `black`,
    `black`,
  ],
  hairType: [
    `thick`,
    `wispy`,
    `straight`,
    `straight`,
    `wavy`,
    `wavy`,
    `curly`,
    `wiry`,
    `oily`,
    `lush`,
    `poofy`,
    `long`,
    `braided`,
    `very long`,
    `greasy`,
    `unruly`,
    `unusually styled`,
    `short cropped`,
  ],
  dndClass: [
    `barbarian`,
    `bard`,
    `cleric`,
    `druid`,
    `fighter`,
    `monk`,
    `rogue`,
    `ranger`,
    `paladin`,
    `sorcerer`,
    `warlock`,
    `wizard`,
  ],
  background: [
    `acolyte`,
    `charlatan`,
    `criminal`,
    `entertainer`,
    `folk hero`,
    `guild artisan`,
    `hermit`,
    `noble`,
    `outlander`,
    `sage`,
    `sailor`,
    `soldier`,
    `urchin`,
  ],
  pockets: [
    `5 cp`,
    `6 cp`,
    `15 cp`,
    `22 cp`,
    `27 cp`,
    `5 sp`,
    `5 sp`,
    `6 sp`,
    `7 sp`,
    `2 gp`,
    `34 cp and 4 sp`,
    `12 sp and 7 gp`,
    `a clove of garlic`,
    `a vial of ink worth 8sp`,
    `hardtack`,
    `an explosive rune, dealing 2d4 fire damage`,
    `a palm-sized glass sphere`,
    `a wooden comb`,
    `fragments of a shattered sword`,
    `a deck of tarot cards`,
    `map of a nearby castle`,
    `map of the local area`,
    `a tin spoon`,
    `a mess kit`,
    `lacy undergarments`,
    `spectacles worth 5gp`,
    `a spool of thread`,
    `a piece of chalk`,
    `a necklace of animal teeth`,
    `a headhunter's contract`,
    `a list of people in a nearby city`,
    `a worn leather strap`,
    `a ring of iron keys`,
    `a flask full of salt water`,
    `a box of candles`,
    `a vial of quicksilver`,
    `a traveller's journal`,
    `a lead amulet`,
    `a signet ring for a noble house`,
    `a list of local taverns`,
    `a golden yellow topaz gem worth 50gp`,
    `a page torn from a spellbook`,
    `scraps of bad poetry`,
    `a pair of bloodstained gloves`,
    `thirteen mouse teeth`,
    `a pouch full of dried berries`,
    `an invitation to a wedding that happened a few weeks ago`,
    `a brass ring`,
    `a shopping list`,
    `the cork from a wine bottle`,
    `a scrap of paper with uninteligible writing on it`,
    `a smoking pipe`,
    `a pouch of ruby powder`,
    `a deed to a ruined tower`,
    `a bottle of honey`,
    `a sling with 10 bullets`,
    `a broken buckle`,
    `a knot of silk ribbons`,
    `a silver pearl worth 10gp`,
    `a potion of Polymorph Self worth 350gp`,
    `1pp wrapped in a crude map`,
    `pocket sand`,
    `a wedge of cheese`,
    `a string of wooden prayer beads`,
    `a lock of hair`,
    `a dead mouse`,
    `a compass`,
    `an empty flask`,
    `85gp`,
    `three diamonds worth 30gp each`,
    `a black pearl worth 50gp`,
    `a black opal worth 100gp`,
  ],
  value: [
    `experience`,
    `family`,
    `progeny`,
    `learning`,
    `wealth`,
    `masterwork`,
    `revenge`,
    `intelligence`,
    `discovery`,
    `pilgrimage`,
    `invention`,
    `miracle`,
    `secret`,
    `martyrdom`,
    `collection`,
    `patronage`,
    `fame`,
  ],
  drive: [
    `health`,
    `beauty`,
    `thrills`,
    `knowledge`,
    `power`,
    `partnership`,
    `networking`,
    `glory`,
    `entertainment`,
    `helpfulness`,
    `bravery`,
    `compassion`,
    `piety`,
    `solitude`,
    `relationships`,
    `hedonism`,
    `privacy`,
  ],
  belief: [
    `piety`,
    `pragmatism`,
    `cleverness`,
    `stoicism`,
    `reason`,
    `self-deserving`,
    `dogma`,
    `forgiveness`,
    `learning`,
    `tough love`,
    `honor`,
    `loyalty`,
    `optimism`,
    `respect`,
    `self-discipline`,
    `integrity`,
  ],
  race: [`human`, `half-elf`, `elf`, `dwarf`, `gnome`, `halfling`, `half-orc`, `dragonborn`, `tiefling`],
  standardLanguages: [`Common`, `Dwarvish`, `Elvish`, `Gnomish`, `Giant`, `Goblin`, `Halfling`, `Orc`],
  exoticLanguages: [
    `Abyssal`,
    `Celestial`,
    `Draconic`,
    `Deep Speech`,
    `Infernal`,
    `Primordial`,
    `Sylvan`,
    `Undercommon`,
  ],
  classTraits: {
    barbarian: {
      dndClassOrigin: [
        `My devotion to my people lifted me in battle, and I learned to control my bloodlust.`,
        `The spirits of my ancestors called out to me to complete a task, so I took up the way of the barbarian.`,
        `I lost control in battle one day, as if something else was guiding me as I slaughtered my enemies.`,
        `I went on a spiritual journey to find myself, and discovered the inner rage that I had could be tamed, used, and controlled.`,
        `I was struck by lightning, but miraculously lived. Ever since that day, I've been stronger, faster, and able to push through any struggle.`,
        `I needed an outlet to channel my anger, otherwise I would have snapped, and killed an innocent person.`,
      ],
      background: [
        `charlatan`,
        `criminal`,
        `folk hero`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `outlander`,
        `outlander`,
        `outlander`,
        `outlander`,
        `outlander`,
        `sailor`,
        `soldier`,
        `soldier`,
        `soldier`,
        `urchin`,
      ],
      weapon: [`a huge greataxe`, `a battleaxe`, `a greatsword`, `two handaxes`, `two warhammers`],
      wealth() {
        return dice(2, 4) * 1000
      },
    },
    bard: {
      dndClassOrigin: [
        `I awakened my latent bardic abilities through trial and error.`,
        `I was a gifted performer, and eventually attracted the attention of a legendary bard, who decided to teach me to further my talents into the realm of magic.`,
        `I joined a society of scholars and orators, who helped teach me how to harness my music and turn it into magic.`,
        `I felt a great calling to recount the tales of heros past, and bring them alive through song and stories.`,
        `I joined one of the great colleges to learn old lore, and did music as an elective.`,
        `I picked up an instrument one day, and found that I could play it perfectly.`,
      ],
      background: [
        `charlatan`,
        `charlatan`,
        `criminal`,
        `entertainer`,
        `entertainer`,
        `entertainer`,
        `entertainer`,
        `entertainer`,
        `entertainer`,
        `folk hero`,
        `folk hero`,
        `guild artisan`,
        `guild artisan`,
        `noble`,
        `outlander`,
        `sailor`,
        `soldier`,
        `urchin`,
      ],
      weapon: [`a crossbow`, `a longsword`, `a longsword`, `a longsword`, `a long bow`, `two daggers`],
      wealth() {
        return dice(5, 4) * 1000
      },
    },
    cleric: {
      dndClassOrigin: [
        `My god called on me to serve the faith as a cleric, so I abandoned my previous life, and set out for the nearest temple.`,
        `I saw the injustice and horrors of the world, and felt that I couldn't live without trying to do something about it.`,
        `My god gave me a sign that I was needed to do something important, some time in the future. I'm still waiting for my time to serve, but when it happens, I'll be ready.`,
        `I've always been devout, but it wasn't until I completed a pilgrimage to a sacred site that I found my true calling.`,
        `I used to serve in the beauracracy of the church, but found the work unrewarding. Being able to spread the message to the farthest corners of the land is much more satisfying work.`,
      ],
      background: [
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `charlatan`,
        `criminal`,
        `entertainer`,
        `folk hero`,
        `folk hero`,
        `folk hero`,
        `guild artisan`,
        `guild artisan`,
        `hermit`,
        `hermit`,
        `noble`,
        `noble`,
        `noble`,
        `sage`,
        `sage`,
        `sage`,
        `sage`,
        `sailor`,
        `soldier`,
        `urchin`,
      ],
      weapon: [`a mace`, `a mace`, `a morning star`, `a club`, `a quarterstaff`, `a crossbow`],
      wealth() {
        return dice(5, 4) * 1000
      },
    },
    druid: {
      dndClassOrigin: [
        `I found a place among a group of druids after I fled a catastrophe.`,
        `I saw too much devastation in the wilds where I used to play for days as a child, and decided to protect the wilderness.`,
        `I have always had an affinity with animals, so I decided to explore it, and found that I had a gift to converse with them.`,
        `I befriended a druid that frequented an old pub, and he convinced me that the world needed me to carry on his work as a druid.`,
        `Whiie l was growing up, I saw spirits all around me— entities no one else could perceive. I sought out the druids to help me understand the visions, and communicate with these beings.`,
      ],
      background: [
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `charlatan`,
        `folk hero`,
        `folk hero`,
        `folk hero`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `noble`,
        `noble`,
        `outlander`,
        `outlander`,
        `outlander`,
        `outlander`,
        `sage`,
        `sage`,
        `sage`,
        `sailor`,
        `soldier`,
        `urchin`,
      ],
      weapon: [
        `a mace`,
        `a mace`,
        `a morning star`,
        `a club`,
        `a quarterstaff`,
        `a crossbow`,
        `a longbow`,
        `a longbow`,
      ],
      wealth() {
        return dice(2, 4) * 1000
      },
    },
    fighter: {
      dndClassOrigin: [
        `I wanted to hone my combat skills, and so I joined a war college`,
        `I  grew up fighting, and I refined my talents by defending myself against people who crossed me.`,
        `I squired for a knight, who taught me how to fight, care for my steed, and conduct myself with honor. I decided to take up that path for myself.`,
        `Monster attacks led me to believe that there was no other way for me to be able to defend my family.`,
        `I joined the army, and learnt how to fight in a group as a team against a common enemy.`,
        `I always had a knack for just about any weapon which I picked up.`,
      ],
      background: [
        `acolyte`,
        `charlatan`,
        `criminal`,
        `criminal`,
        `criminal`,
        `entertainer`,
        `folk hero`,
        `folk hero`,
        `folk hero`,
        `guild artisan`,
        `hermit`,
        `noble`,
        `outlander`,
        `outlander`,
        `sage`,
        `sailor`,
        `sailor`,
        `sailor`,
        `soldier`,
        `soldier`,
        `soldier`,
        `soldier`,
        `soldier`,
        `soldier`,
        `urchin`,
      ],
      weapon: [
        `a huge greataxe`,
        `a battleaxe`,
        `a greatsword`,
        `a long sword`,
        `a long sword`,
        `a long sword`,
        `a long sword`,
        `a long bow`,
        `a short sword`,
        `a war pick`,
        `a falcheon`,
        `a halberdier`,
      ],
      wealth() {
        return dice(5, 4) * 1000
      },
    },
    monk: {
      dndClassOrigin: [
        `I stumbled into a portal and took refuge in a strange monastery, where I learned how to defend mysel fagainst the forces of darkness.`,
        `I was chosen to study at a secluded monastery, where I learnt the fundamental techniques to set me on the path to eventual mastery.`,
        `I sought out the instruction of a monk to gain a greater understanding of my world, and my purpose in it.`,
        `I was overwhelmed with grief when I lost my sister, and found solace in meditation with the monks.`,
        `I always felt a power within me, and sought out an order of monks to help me understand it and harness that energy for good.`,
        `I was wild, and undisciplined as a child, until I realised the error of my ways. I sought out the monks to atone for my sins.`,
      ],
      background: [
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `charlatan`,
        `criminal`,
        `folk hero`,
        `guild artisan`,
        `hermit`,
        `hermit`,
        `hermit`,
        `noble`,
        `noble`,
        `outlander`,
        `sage`,
        `sage`,
        `sage`,
        `soldier`,
        `urchin`,
      ],
      weapon: [`fists`, `fists`, `fists`, `a quarterstaff`, `a quarterstaff`],
      wealth() {
        return dice(2, 4) * 100
      },
    },
    paladin: {
      dndClassOrigin: [
        `A magical being appeared before me, and called on me to undertake a holy quest.`,
        `One of my ancestors left a holy quest unfulfilled, so I seek to rectify this.`,
        `The world is a dark and terrible place. I seek to be a beacon of hope for those that may not have the courage to go on otherwise.`,
        `I served as a paladin's squire, and admired his honesty and conduct. I decided to follow in his footsteps, and champion the good and decency that he represented.`,
        `Evil must be opposed on all fronts, and I decided to be the first line of defense against such scum.`,
        `Becoming a paladin was a natural consequence of my unwavering faith. I saw the need for the faith to be protected with sword and shield.`,
      ],
      background: [
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `charlatan`,
        `criminal`,
        `entertainer`,
        `folk hero`,
        `folk hero`,
        `folk hero`,
        `folk hero`,
        `guild artisan`,
        `hermit`,
        `noble`,
        `noble`,
        `noble`,
        `noble`,
        `noble`,
        `outlander`,
        `sage`,
        `sailor`,
        `soldier`,
        `soldier`,
        `soldier`,
        `soldier`,
        `soldier`,
        `urchin`,
        `urchin`,
        `urchin`,
        `urchin`,
      ],
      weapon: [
        `a greatsword`,
        `a long sword`,
        `a long sword`,
        `a long sword`,
        `a short sword`,
        `a war pick`,
        `a falcheon`,
        `a halberdier`,
      ],
      wealth() {
        return dice(5, 4) * 1000
      },
    },
    ranger: {
      dndClassOrigin: [
        `I always had a way with animals, and was able to calm them with a gentle touch and soothing word.`,
        `I found purpose while I was honing my hunting skills by bringing dangerous beasts down from the outskirts of civilisation.`,
        `I suffer from wanderlust, so I found the life of the ranger to be freeing; to me, wandering without a fixed home is freeing.`,
        `I met a grizzled ranger who taught me the secrets of woodcraft and surviving in the wild.`,
        `I served in the army, and led my division by scouting ahead, blazing trails and tracking our enemies.`,
      ],
      background: [
        `acolyte`,
        `acolyte`,
        `charlatan`,
        `criminal`,
        `entertainer`,
        `folk hero`,
        `folk hero`,
        `folk hero`,
        `folk hero`,
        `guild artisan`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `outlander`,
        `outlander`,
        `outlander`,
        `outlander`,
        `sage`,
        `sailor`,
        `soldier`,
        `soldier`,
        `soldier`,
        `urchin`,
      ],
      weapon: [
        `a crossbow`,
        `a longsword`,
        `a longsword`,
        `a longsword`,
        `a long bow`,
        `a long bow`,
        `a long bow`,
        `two daggers`,
      ],
      wealth() {
        return dice(4, 4) * 1000
      },
    },
    rogue: {
      dndClassOrigin: [
        `I've always been nimble and quick of wit, so I decided to use those talents to help me make my way in the world.`,
        `A thief wronged me, so I focused my training on mastering those skills to better combat foes of that sort.`,
        `Know thy enemy. I aim to learn everything there is to know about the Thieves' guild, and then I'll bring it all tumbling down.`,
        `An experienced rogue saw something in me, and taught me several useful tricks.`,
        `I took up with a group of ruffians, that taught me how to get what I want without direct confrontation.`,
        `I'm a sucker for a shiny bauble or bag of coins, as long as I can get it without risking life and limb.`,
        `I just love the thrill of the heist. There's nothing that makes me feel more alive than taking something from right under someone's nose.`,
      ],
      background: [
        `charlatan`,
        `charlatan`,
        `charlatan`,
        `criminal`,
        `criminal`,
        `criminal`,
        `criminal`,
        `criminal`,
        `criminal`,
        `folk hero`,
        `folk hero`,
        `guild artisan`,
        `guild artisan`,
        `hermit`,
        `noble`,
        `noble`,
        `outlander`,
        `sailor`,
        `soldier`,
        `urchin`,
        `urchin`,
        `urchin`,
        `urchin`,
        `urchin`,
      ],
      weapon: [
        `a long sword`,
        `a long sword`,
        `two daggers`,
        `two daggers`,
        `two daggers`,
        `two daggers`,
        `a crossbow`,
        `a crossbow`,
        `a crossbow`,
      ],
      wealth() {
        return dice(4, 4) * 1000
      },
    },
    sorcerer: {
      dndClassOrigin: [
        `When I was born, all of the milk turned to cheese. My family is convinced that it was a harbinger for my powers.`,
        `I suffered a terrible strain, which brought forth my dormant powers. I have fought to control it ever since.`,
        `My immediate family never spoke of my ancestors, and when I asked, they would change the subject. It wasn't until I started displaying strange talents that the full truth of my heritage came out.`,
        `A monster attacked one of my friends when I was younger, and I lashed out in a burst of energy, saving my friend, but unlocking the torrent of power which I still struggle to control.`,
        `After a magical conflagration, I realised that while I was unharmed, I had been fundamentally changed by the outburst of magical energy. I'm only just beginning to understand what has happened to me.`,
      ],
      background: [
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `charlatan`,
        `charlatan`,
        `charlatan`,
        `charlatan`,
        `criminal`,
        `entertainer`,
        `entertainer`,
        `folk hero`,
        `folk hero`,
        `guild artisan`,
        `hermit`,
        `noble`,
        `noble`,
        `noble`,
        `outlander`,
        `sage`,
        `sage`,
        `sage`,
        `sailor`,
        `soldier`,
        `urchin`,
      ],
      weapon: [
        `a crossbow`,
        `a longsword`,
        `a longsword`,
        `a longsword`,
        `a long bow`,
        `two daggers`,
        `a dagger`,
        `a dagger`,
      ],
      wealth() {
        return dice(3, 4) * 1000
      },
    },
    warlock: {
      dndClassOrigin: [
        `I was examining a strange tome I found in an abandoned library when the entity that would become my patron suddenly appeared before me.`,
        `While wandering through a forbidden place, I came across a magical entity, which offered to form a pact with me.`,
        `I stumbled into the clutches of my patron after I accidentally stepped through a magical doorway.`,
        `During a crisis, I prayed for any being to help me. The creature that answered was my patron.`,
        `My future patron visited me in my dreams, and offered great power in exchange for my servie.`,
        `One of my ancestors had a pact with my patron, which bound me to the same fate.`,
      ],
      background: [
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `charlatan`,
        `criminal`,
        `entertainer`,
        `folk hero`,
        `guild artisan`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `noble`,
        `noble`,
        `noble`,
        `outlander`,
        `sage`,
        `sage`,
        `sage`,
        `sage`,
        `sage`,
        `sailor`,
        `soldier`,
        `urchin`,
      ],
      weapon: [
        `a crossbow`,
        `a quarterstaff`,
        `a quarterstaff`,
        `a quarterstaff`,
        `a longsword`,
        `a dagger`,
        `a dagger`,
        `a dagger`,
      ],
      wealth() {
        return dice(4, 4) * 1000
      },
    },
    wizard: {
      dndClassOrigin: [
        `An old wizard chose me from among several candidates to serve an apprenticeship.`,
        `When I became lost in a magical forest, a hedge wizard took me in, and taught me the fundamentals of magic so that I could navigate my way out.`,
        `I grew up listening to tales of great wizards that could change reality with a flick of their hand. I knew from a young age that I wanted to hold that sort of power.`,
        `One of my relatives was an accomplished wizard in their own right, and they recognised the same potential in me that their mentor saw in them.`,
        `While exploring the restricted section of a library, I came across a magical tome, which sparked the interest in me.`,
        `I was a prodigy that demonstrated mastery of the arcane arts at a very young age. When I became old enough to set out on my own, I did so to continue my studies and expand my powers.`,
      ],
      background: [
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `acolyte`,
        `charlatan`,
        `criminal`,
        `entertainer`,
        `folk hero`,
        `guild artisan`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `hermit`,
        `noble`,
        `noble`,
        `noble`,
        `outlander`,
        `sage`,
        `sage`,
        `sage`,
        `sage`,
        `sage`,
        `sailor`,
        `soldier`,
        `urchin`,
      ],
      weapon: [
        `a crossbow`,
        `a quarterstaff`,
        `a quarterstaff`,
        `a quarterstaff`,
        `a longsword`,
        `a longsword`,
        `a longsword`,
        `a dagger`,
      ],
      wealth() {
        return dice(4, 4) * 1000
      },
    },
  },
  backgroundTraits: {
    "acolyte": {
      // 'knownLanguages': function (npc) {
      //   var allLanguages = setup.npcData.standardLanguages.concatUnique(setup.npcData.exoticLanguages)
      //   var availableLanguages = allLanguages.delete(npc.knownLanguages)
      //   return availableLanguages.pluck()
      // },
      extraLanguage: true,
      backgroundOrigin: [
        `I ran away from home at a young age, and found refuge in a temple.`,
        `My family gave me to a temple, since they were unable to care for me.`,
        `I grew up in a household with strong religious convictions. Entering the service of the Gods seemed to be the natural progression.`,
        `An impassioned sermon struck a chord deep in me, and compelled me to serve the faith.`,
        `I followed a childhood friend into religious service because we made a pact to never be apart.`,
        `I followed a lover into religious service, but tragically, they were killed. The faith was the only thing that stopped me from ending my own life.`,
      ],
      ideal: [
        `I believe that the ancient traditions of worship and sacrifice must be preserved and upheld.`,
        `I always try to help those in need, no matter what the personal cost.`,
        `We must help bring about the changes the gods are constantly working in the world.`,
        `I hope to one day rise to the top of my faith's religious hierarchy.`,
        `I trust that my deity will guide my actions, I have faith that if I work hard, things will go well.`,
        `I seek to prove myself worthy of my god's favor by matching my actions against their teachings.`,
      ],
      personalityTrait: [
        `I idolize a particular hero of my faith, and constantly refer to that person’s deeds and example.`,
        `I can find common ground between the fiercest of enemies, and can work towards peace no matter what the conditions.`,
        `I see omens in every event and action. The gods try to speak to us, we just need to listen!`,
        `Nothing can shake my optimistic attitude.`,
        `I quote (or misquote) sacred texts and proverbs in almost every situation.`,
        `I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.`,
        `I've enjoyed fine food, drink, and high society among my temple’s elite. Rough living grates on me.`,
        `I’ve spent so long in the temple that I have little practical experience dealing with people in the outside world.`,
      ],
      bond: [
        `I would die to recover an ancient artifact of my faith that was lost long ago.`,
        `I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.`,
        `I owe me life to the priest who took me in when my parents died.`,
        `Everything I do is for the common people.`,
        `I will do anything to protect the temple where I served.`,
        `I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.`,
      ],
      wealth: 1500,
    },
    "charlatan": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `As a youngster, I was left to my own devices. My knack for manipulating people helped me survive.`,
        `I learned early on that people are easy to exploit, and are gullible and too trusting.`,
        `I often got into trouble as a youngster, but talked my way out of it.`,
        `I took up cheating as a hobby, then was sort of adopted by a local scam artist. It just sort of became a way of life for me.`,
        `After a charlatan fleeced my family, I decided to learn all the tricks I could so I would never fall for another scam.`,
      ],
      ideal: [
        `I am a free spirit– no one tells me what to do.`,
        `I never target people who can't afford to lose a few coins.`,
        `I distribute the money I acquire to the people who really need it.`,
        `I never run the same con twice.`,
        `I believe that Material goods come and go. Bonds of friendship last forever.`,
        `I'm determined to make something of myself.`,
      ],
      personalityTrait: [
        `I fall in and out of love easily, and am always pursuing someone.`,
        `I have ajoke for every occasion, especially occasions where humor is inappropriate.`,
        `Flattery is my preferred trick for getting what I want.`,
        `I’m a born gambler who can't resist taking a risk for a potential payoff.`,
        `I lie about almost everything, even when there’s no good reason to.`,
        `Sarcasm and insults are my weapons of choice.`,
        `I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.`,
        `I pocket anything I see that might have some value.`,
      ],
      bond: [
        `I fleeced the wrong person, a lord called <<print setup.raceTraitsData["human"].genderTraits["man"].randomValue(firstName)>>, and must work to ensure that he never crosses paths with me or those I care about.`,
        `I owe everything to my mentor <<print setup.raceTraitsData['human'].genderTraits['man'].randomValue(firstName)>>--a horrible person who's probably rotting in jail somewhere.`,
        `Somewhere out there I have a child, litte <<print setup.raceTraitsData['human'].genderTraits['man'].randomValue(firstName)>>, who doesn't know me. I'm going to try and make the world better for him.`,
        `I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.`,
        `A powerful person, Lord <<print setup.raceTraitsData['human'].genderTraits['man'].randomValue(firstName)>>, killed someone I love. Some day soon, I'll have my revenge.`,
        `I swindled and ruined a person who didn't deserve it, and now I seek to atone for my misdeeds but might never be able to forgive myself.`,
      ],
      wealth: 1500,
    },
    "criminal": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `I resented authority in my younger days, and I saw a life of crime as a way to get back at those that I thought had wronged me.`,
        `I resented authority as a youngster, and saw a life of crime as the best way to fight back against tyranny and oppression.`,
        `I fell in with a gang of reprobates and ne’er-do- wells, and I learned my specialty from them.`,
        `A relative taught me the trade to prepare me for the family trade.`,
        `I left home at a relatively young age, and found refuge in a thieves' guild.`,
        `I was always bored, so I started committing minor crimes to pass the time. The adrenaline rush was addictive, and soon I was going on to bigger and better heists.`,
      ],
      ideal: [
        `I believe in honour amongst thieves- I don't steal from others in the trade.`,
        `I am definitely a fan of freedom- Chains are meant to be broken`,
        `I steal from the wealthy so that I can help people in need.`,
        `I will do whatever it takes to become wealthy.`,
        `I'm loyal to my friends`,
        `I believe that there's a spark of good in everyone.`,
      ],
      personalityTrait: [],
      bond: [
        `I'm trying to pay off an old debt I owe to a generous benefactor.`,
        `My ill-gotten gains go to support my family.`,
        `Something important was taken from me, and I aim to steal it back.`,
        `I will become the greatest thief that ever lived.`,
        `I'm guilty of a terrible crime. I hope I can redeem myself for it.`,
        `Someone I loved died because of a mistake I made. That will never happen again.`,
      ],
      wealth: 1500,
    },
    "entertainer": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `Members of my family made ends meet by performing, so it was fitting for me to follow their example`,
        `I always had a keen insight into what made other people laugh and cry. A life as an entertainer seemed to be the natural continuation of that.`,
        `I saw a bard perform once, and it inspired me so much that I decided to follow in his footsteps.`,
        `I ran away from home to join a minstrel troupe.`,
        `I earned extra coin by performing on the streets as a child, and I never seemed to stop.`,
        `A traveling entertainer took me in to teach me the trade, and I learned to love it.`,
      ],
      ideal: [
        `When I perform, I want to make beautiful things for the pleasure of my audience`,
        `The stories I tell have a lot of history which I wish to preserve.`,
        `The world is in need of new ideas and bold action.`,
        `I'm only in it for the money and fame.`,
        `I like seeing the smiles on people's faces when I perform. That's all that matters.`,
        `Art should reflect the soul; it should come from within and reveal who we really are.`,
      ],
      personalityTrait: [],
      bond: [
        `My instrument is my most treasured possession, and it reminds me of someone I love.`,
        `Someone stole my precious instrument, and someday I'll get it back.`,
        `I want to be famous, whatever it takes.`,
        `I idolize a hero of the old tales and measure my deeds against that person's.`,
        `I will do anything to prove myself superior to my hated rival.`,
        `I would do anything for the other members of my old party.`,
      ],
      wealth: 1500,
    },
    "folk hero": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `I learned what was right and wrong from my family.`,
        `I was always enamored by tales of heroes and wished I could be something more than ordinary.`,
        `I hated my mundane life, so when it was time for someone to step up and do the right thing, I took my chance.`,
        `One of my relatives was an adventurer, and l was inspired by that person’s courage.`,
        `A mad old hermit spoke a prophecy when l was born, saying that I would accomplish great things.`,
        `I have always stood up for those who are weaker than me.`,
      ],
      ideal: [
        `I have the radical belief that people deserve to be treated with dignity and respect.`,
        `I believe that no one should get preferential treatment before the law`,
        `Tyrants must not be allowed to oppress the people.`,
        `If I become strong, I will be better able to protect people.`,
        `There's no good in pretending to be something I'm not.`,
        `Nothing and no one can steer me away from my higher calling.`,
      ],
      personalityTrait: [],
      bond: [
        `I have a family, but I have no idea where they are.  One day, I hope to see them again.`,
        `I worked the land, I love the land, and I will protect the land.`,
        `A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.`,
        `My tools are symbols of my past life, and I carry them so that I will never forget my roots.`,
        `I protect those who cannot protect themselves.`,
        `I wish my childhood sweetheart had come with me to pursue my destiny.`,
      ],
      wealth: 1000,
    },
    "gladiator": {
      backgroundOrigin: [
        `I found myself in a fight, and the drunkards around me started to bet on whether I would win. I found that strangely exhilarating, and continued to fight, seeking that thrill.`,
        `I was a slave, and was forced to fight for my supper and eventual freedom. By the time I got out, there was nothing else I knew.`,
        `I entered a fight as a drunken bet, and somehow managed to win. The money was too good for me to quit.`,
        `I was constantly getting into fights as a youngster. I figured I might as well continue, for money.`,
      ],
      ideal: [
        `If I become strong, I will be better able to protect people.`,
        `I want to become the hero I pretend to be.`,
        `I want people to tremble at the sound of my name.`,
        `I want to inspire others.`,
        `I am in it for the money.`,
        `I honestly love to see others in pain.`,
      ],
      personalityTrait: [],
      bond: [
        `My weapon has seen me through many a battle, and it means everything to me.`,
        `The costume that I wear when fighting is part of me and my being.`,
        `I have seen countless friends die around me, many at my own hands, so I find it difficult to make new ones.`,
        `I am loyal to my friends as long as I respect them.`,
        `I feel like I am still a part of my old arena team.`,
        `Sometimes, I feel like I cannot leave who I was in the arena.`,
      ],
      wealth: 1500,
    },
    "guild artisan": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `I was apprenticed to a master who taught me the guild’s business.`,
        `I helped a guild artisan keep a secret, and in return, I was taken on as an apprentice.`,
        `One of my relatives who belonged to the guild made a place for me.`,
        `I was always good with my hands, so I figured that I would make something of it.`,
        `I wanted to get away from my home situation and start a new life, so I learned a trade in secret and ran away one night.`,
        `I learned the essentials from an old mentor, but I had to join a guild to finish my learning once he passed away.`,
      ],
      ideal: [
        `I believe it is the duty of all civilized people to strengthen the bonds of community and the security of civilization.`,
        `My talents were given to me so that I could use them to benefit the world.`,
        `Everyone should be free to pursue their own livelihood.`,
        `I'm only in it for the money.`,
        `I'm committed to the people I care about`,
        `I work hard to be the best there is at my craft.`,
      ],
      personalityTrait: [],
      bond: [
        `The workshop where I learned my trade is the most important place in the world to me.`,
        `I created a great work for someone, and then found them unworthy to receive it; I'm still looking for someone worthy.`,
        `I owe my guild a great debt for forging me into the person I am today.`,
        `I pursue wealth to secure someone's love.`,
        `One day I will return to my guild and prove that I am the greatest artisan of them all.`,
        `I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.`,
      ],
      wealth: 1500,
    },
    "hermit": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `My enemy ruined my reputation, and I had to flee to a life of solitude to escape further disparagement.`,
        `I am comfortable with isolation, as I seek inner peace.`,
        `I find myself in love with nature, and prefer the company of the animals and plants to that of people.`,
        `I never liked the people that I grew up with, so it was easy for me to leave it all behind and strike out a new life, alone.`,
        `I felt compelled to forsake my past, and did so with great reluctane. Even now, I sometimes regret my decisions.`,
      ],
      ideal: [
        `My gifts are meant to be shared with all`,
        `I believe that motions must not cloud our sense of what is right and true`,
        `I believe that inquiry and curiosity are the pillars of progress.`,
        `I think that solitude and contemplation are paths toward mystical or magical power.`,
        `I believe that meddling in the affairs of others only causes trouble.`,
        `If you know yourself, you know your enemy.`,
      ],
      personalityTrait: [],
      bond: [
        `Nothing is more important than the other members of my hermitage, order, or association.`,
        `I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.`,
        `I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.`,
        `I entered seclusion because I loved someone I could not have.`,
        `Should my discovery come to light, it could bring ruin to the world.`,
        `My isolation gave me great insight into a great evil that only I can destroy.`,
      ],
      wealth: 500,
    },
    "noble": {
      // 'knownLanguages': function (npc) {
      //   var allLanguages = setup.npcData.standardLanguages.concatUnique(setup.npcData.exoticLanguages)
      //   var availableLanguages = allLanguages.delete(npc.knownLanguages)
      //   return availableLanguages.pluck()
      // },
      extraLanguage: true,
      backgroundOrigin: [
        `My family has been disgraced, and I intend to restore our once pristine reputation.`,
        `I come from an old and storied family, and it fell to me to preserve the family name.`,
        `My family recently came by its title, and that elevation thrust us into a new and strange world.`,
        `My family has a title, but none of my ancestors have done anything of note.`,
        `My family is filled with remarkable people. I hope to live up to their reputation.`,
        `I hope to increase my family's power and influence.`,
      ],
      ideal: [
        `Respect is due to me because of my position`,
        `It is my duty to respect the authority of those above me`,
        `I must prove that I can handle myself without the coddling of my family.`,
        `If I can attain more power, I will be able to protect my family`,
        `I believe that blood runs thicker than water.`,
        `It is my duty to protect and care for the people beneath me.`,
      ],
      personalityTrait: [],
      bond: [
        `I will face any challenge to win the approval of my family.`,
        `My house's alliance with another noble family must be sustained at all costs.`,
        `Nothing is more important that the other members of my family.`,
        `I am in love with the heir of a family that my family despises.`,
        `My loyalty to my sovereign is unwavering.`,
        `The common folk must see me as a hero of the people.`,
      ],
      wealth: 2500,
    },
    "outlander": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `I spent a lot of time in the wilderness as a youngster, and I came to love that way of life.`,
        `From a young age, I couldn't abide the stink of cities, and sought out the wilderness for respite from the chaos of people.`,
        `I came to understand the darkness that lurks in the wilds, and l vowed to combat it.`,
        `My people live on the edges of civilisation, and I learned the methods of survival from my family.`,
        `After a personal tragedy, I retreated to the wilderness to be alone with my thoughts.`,
        `My family moved away from civilisation, and I learnt to adapt with the harsh environment.`,
      ],
      ideal: [
        `I think that life is like the seasons, change should be embraced!`,
        `It is each person's responsibility to make the most happiness for the whole tribe.`,
        `If I dishonor myself, I bring dishonor to my whole tribe`,
        `I believe that the strongest are meant to rule.`,
        `The natural world is more important than all the constructs of civilization.`,
        `I must earn glory in battle.`,
      ],
      personalityTrait: [],
      bond: [
        `My family, clan, or tribe is the most important thing in my life, even when they are far from me.`,
        `An injury to the unspoiled wilderness of my home is an injury to me.`,
        `I will bring terrible wrath down on the evildoers who destroyed my homeland.`,
        `I am the last of my tribe, and it is up to me to ensure their names enter legend.`,
        `I suffer awful visions of a coming disaster and will do anything to prevent it.`,
        `It is my duty to provide children to sustain my tribe.`,
      ],
      wealth: 1000,
    },
    "sage": {
      // 'knownLanguages': function (npc) {
      //   var allLanguages = setup.npcData.standardLanguages.concatUnique(setup.npcData.exoticLanguages)
      //   var availableLanguages = allLanguages.delete(npc.knownLanguages)
      //   return availableLanguages.pluck()
      // },
      extraLanguage: true,
      backgroundOrigin: [
        `I was naturally curious, so I packed up and went to a university to learn more about the world.`,
        `My mentor’s teachings opened my mind to new possibilities in that field of study.`,
        `I was always an avid reader, and became a sage to learn more from the thousands of books that I tended to.`,
        `I discovered an old library and pored over the texts I found there. That experience awakened a hunger in me for knowledge that I still seek.`,
        `I impressed a traveling wizard, who told me that I was squandering my talents and that I should seek out an education to take advantage of my gifts.`,
        `My father gave me a basic education which whetted my appetite for more knowledge, and I left home to build on what I knew.`,
      ],
      ideal: [
        `I believe that the path to power and self-improvement is through knowledge.`,
        `What is beautiful points us beyond itself toward what is true.`,
        `I believe that emotions must not cloud our logical thinking.`,
        `I believe that nothing should fetter the infinite possibility inherent in all existence.`,
        `Knowledge is, in my opinion, the path to power and domination.`,
        `I think that the goal of a life of study is the betterment of oneself.`,
      ],
      personalityTrait: [],
      bond: [
        `It is my duty to protect my students.`,
        `I have an ancient text that holds terrible secrets that must not fall into the wrong hands.`,
        `I work to preserve a library, university, scriptorium, or monastery.`,
        `My life's work is a series of tomes related to a specific field of lore.`,
        `I've been searching my whole life for the answer to a certain question.`,
        `I sold my soul for knowledge; I hope to do great deeds and win it back.`,
      ],
      wealth: 1000,
    },
    "sailor": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `I was press-ganged by pirates and forced to serve as a deck-hand on their ship until I could escape from their clutches.`,
        `I wanted to see the world, so I signed on as a deck- hand for a merchant ship.`,
        `One of my relatives was a sailor, and took me to sea when I was young, which inspired a life-long love of the oceans and the water.`,
        `I needed to escape from town quickly, so I stowed away on a ship. They found me out, and force me to work as a deck-hand as payment for my passage.`,
        `Reavers attacked my village, and I found refuge in a ship.`,
        `There were few prospects where I was living, so I hopped on board a boat, to seek my fortunes elsewhere.`,
      ],
      ideal: [
        `I believe that the thing that keeps a ship together is mutual respect between captain and crew.`,
        `We all do the work. That is how the work gets done.`,
        `To me, the sea is freedom– the freedom to go anywhere and do anything.`,
        `I'm a predator, and I'm not going to apologise for it. Those that cannot survive on the seas should not live.`,
        `I'm committed to my crewmates.`,
        `Someday I'll own my own ship and chart my own destiny.`,
      ],
      personalityTrait: [],
      bond: [
        `I'm loyal to my captain first, everything else second.`,
        `The ship is most important--crewmates and captains come and go.`,
        `I'll always remember my first ship.`,
        `In a harbor town, I have a paramour whose eyes nearly stole me from the sea.`,
        `I was cheated of my fair share of the profits, and I want to get my due.`,
        `Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.`,
      ],
      wealth: 1500,
    },
    "soldier": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `I wanted fame and fortune, so I signed up to the militia to prove my mettle. I don't think I knew what I was doing, but my determination carried me through my contract, and I never stopped.`,
        `I wanted to protect my village from monsters, so I learnt swordcraft and how to fight. Then I learnt that you could earn coin for it, too.`,
        `I was forced to enlist in the local militia to fight for my lord. Many of my friends are dead because of him.`,
        `Invaders attacked my village, and I vowed to never let my family be unprotected again, so I picked up the sword.`,
        `I was always playing with a sword as a kid, and it wasn't until a visiting adventurer sparred with me for fun that I realised that I had a real talent.`,
      ],
      ideal: [
        `Our lot is to lay down our lives in defense of others.`,
        `I do what I must and obey just authority.`,
        `When people follow orders blindly, people die.`,
        `In life, as in war. That is my motto, that I will live and die by.`,
        `To me, ideals aren't worth killing over or going to war for.`,
      ],
      personalityTrait: [],
      bond: [
        `I would lay down my life for the people I served with.`,
        `Someone saved my life on the battlefield. To this day, I will never leave a friend behind.`,
        `My honor is my life.`,
        `I'll never forget the crushing defeat my company suffered or the enemies who dealt it.`,
        `Those who fight beside me are those worth dying for.`,
        `I fight for those who cannot fight for themselves.`,
      ],
      wealth: 1000,
    },
    "urchin": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `My parents died, leaving nobody to look after me, so I took care of myself.`,
        `I had to escape my homelife. I lived off crumbs and scraps, but it was better than the alternative.`,
        `Raiders attacked my village when I was a child, leaving me the only survivor. I had to walk for three days to the next town over, and begged to survive.`,
        `My family was swindled, and we lost everything we had. I had to beg on the streets to look after my family.`,
        `A thief took me in, and in exchange for food and shelter, I would keep an eye on the streets while he pulled off heists.`,
      ],
      ideal: [
        `All people deserve respect.`,
        `We have to take care of each other to survive.`,
        `The low are lifted up, and we all benefit from that.`,
        `The rich need to be shown what life and death are like in the gutters.`,
        `I help the people who help me– that's what keeps us alive.`,
        `I'm going to prove that I'm worthy of a better life.`,
      ],
      personalityTrait: [],
      bond: [
        `My town or city is my home, and I'll fight to defend it.`,
        `I sponsor an orphanage to keep others from enduring what I was forced to endure.`,
        `I owe my survival to another urchin who taught me to live on the streets.`,
        `I owe a debt I can never repay to the person who took pity on me.`,
        `I escaped my life of poverty by robbing an important person, and I'm wanted for it.`,
        `No one else is going to have to endure the hardships I've been through.`,
      ],
      wealth: 1500,
    },
    "commoner": {
      // 'knownLanguages': function (npc) { return npc },
      backgroundOrigin: [
        `I was born into poverty. I've slowly worked my way to where I am today.`,
        `I had a bad string of bets which left me with no other choice than to skip town.`,
        `I was born into a lowly family, and that's where I'll likely stay.`,
        `I was a soldier in the army, with a lot of potential. But then, I made a tactical mistake, which led to my dismissal.`,
        `I was found guilty of a crime that I did not commit, and was sentenced to serfdom.`,
        `I grew up in a loving household, but all the love in the world could not pay the debts which we had.`,
        `I was one of many children, and when I was old enough to work, my parents put me to it.`,
        `I was one of many children, and had to work from a young age to support my family.`,
        `I was the eldest child. When my father died, I had to leave school and work to support my family.`,
      ],
      ideal: [
        `Everyone needs to pitch in for the greater good.`,
        `You have to respect all people`,
        `We have to take care of each other`,
        `The low are lifted up`,
        `The rich need to be shown what life and death are like in the gutters.`,
        `I help the people who help me– that's what keeps us alive.`,
        `I'm going to prove that I'm worthy of a better life.`,
      ],
      personalityTrait: [],
      bond: [
        `I am trying to pay off a debt that I inherited from my father.`,
        `I was swindled out of a large inheritance, and had to go into hiding to keep my family safe.`,
        `I was a nobleman once, but made the wrong man an enemy.`,
        `I had to sell a magical heirloom to pay off a debt. Now I want to buy it back.`,
        `When wandering through a forest, I found a portal to another realm. When I took others to it, it had disappeared. One day I'll find it again.`,
        `I followed my beloved here, and we made a life together, until raiders took them in the night. One day, I'll have my revenge.`,
        `A witch-doctor had claimed to be able to cure my baby. The bastard had lied, and he died at just six weeks. I'll find him one day, and make him wish he had never been born.`,
        `I live for the sea; nothing gives me more pleasure than fishing off my boat.`,
        `My home was a simple one, but it had a certain charm about it. An arsonist burnt it down, and I intend to catch them.`,
        `The lord that took my daughter as a guarantee for my debt never intended to return her. I intend to make him.`,
        `I love the quiet life. Nothing disturbs me more than a disturbance of the peace.`,
        `My friends are my world. If my life consists of working for five days, then going to the tavern with my buddies, I will be content.`,
        `I know my lot in life; feudalism dictates that one should serve the other. I disagree, and will fight to my dying breath to change the system.`,
        `I can't change the past, but I can change my future. I'll work harder and better to provide a better life for my children.`,
        `My father was a drunkard, a gambler, and an abusive man. I will break the cycle.`,
        `I want to perfect my craft. Nothing gives me more satisfaction than someone praising my work.`,
        `When my mother died, I found a list of men in her possessions. One of them is my father. I'll find him.`,
        `When I was young, my parents died, and the church took me in. I'll spread the good word, and the work that they do.`,
        `My father taught me how to read. All I want to do in life is to further my knowledge on how the world works.`,
        `I never learnt how to read. One day, I will be able to tell my son what the words on parchment mean.`,
        `I have a tendency to gamble away my earnings. This is the third town I've moved to to escape debtors.`,
        `My livelihood depended on a horse, which an adventurer took off with. I'll make him pay.`,
        `I used to fear anyone who didn't look like me until some adventurers from distant lands saved my life. Now I want to see the whole world and the planes beyond.`,
        `My lord raised the taxes to absurd levels so he could conscript people as punishment. I broke into my lord's manor one night, took a string of pearls, and sold it. I'll never forget that thrill.`,
        `I have a knack for magic but my parents couldn't afford a tutor. I want to become the mage I knew I could be.`,
        `I am the fifth child and will not inherit anything. I need to find somewhere I can settle down.`,
        `I was a farmer, got conscripted, went off to war, and came back broken. I want my grandchildren to have peaceful lives.`,
        `I got really drunk, fell asleep in a box that got loaded on a boat, and wound up in a big city I've never heard of. My village is so small and secluded I don't even know what country it's in! How do I get home?`,
        `I was the cook for a band of thieves who lived in a forest and stole from the rich to give to the poor. They all got arrested. I need another job I guess.`,
        `I was an ordinary maid in a vampire's castle. Some adventurers staked my former boss. I have to readjust to living with the living.`,
        `I was the village priest but lost my church when a charismatic preacher moved in and converted all my worshipers. I need a sign from heaven to restore my faith.`,
        `I love haggling, meeting new folks, and helping people find what they need. My dream is to build the finest tavern and shop.`,
        `I was petrified 1000 years ago by a medusa while foraging for mushrooms. A wizard found and cured me but left without explaining anything. I must readjust and relearn everything!`,
      ],
      wealth: 500,
    },
  },
  professionTraits: {
    bartender: {
      dndClassOrigin: [
        `I came across $tavern.name as a youngster, and spent many a night here drinking with my buddies. When the old owner died, it went to auction, and I tried to kep the dream alive by buying it. One by one all my friends grew out of it, or moved away.`,
        `Before I ran $tavern.name, it was my dad's. I kept the family business going to support him in his old age.`,
        `When I first got to $town.name, it was practically a ghost town. We built $tavern.name as a social hub for the folk, and it's now what it is today.`,
        `The old owner was a problem gambler, and when they auctioned off $tavern.name, I jumped at it.`,
        `The old owner thought that $tavern.name wasn't profitable. In the first six months of my stewardship, I turned it around, and have made it the best bloody pub in $town.name!`,
        `Running $tavern.name was the family business, and it was always going to be my lot in life. I'm not angry or disappointed or anything, but I would like to see the world one day, and it stops me from doing that.`,
        `I was just a kitchen hand when this place started. The owner and I worked through thick and thin, and when his daughter died, he had nobody to leave it to, except for me.`,
        `My parents bought this place as an investment. I don't know what they were thinking- when have you ever heard of a pub being profitable?`,
      ],
      background: [
        `urchin`,
        `urchin`,
        `urchin`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `noble`,
        `noble`,
        `noble`,
      ],
      weapon: [`a crossbow`, `a longsword`, `a longsword`, `a longsword`, `a dagger`],
      wealth: 1400,
    },
    blacksmith: {
      dndClassOrigin: [
        `I was an apprentice in $smithy.name, and took up the title when my old master passed on.`,
        `I was a tinkerer, and just drifted from town to town doing odd jobs for people until I came to $town.name. I fell in love with the place, and then settled here.`,
        `I followed my love here, set up shop, and now we're happily married, with a steady job and a roof over our heads.`,
        `My father was a blacksmith before me, and then I took up the trade to make him proud. Or at least, I hope I've made him proud. He passed before I opened up shop.`,
        `I was an apprentice, and my old master bitterly despised me because my father married his love. I worked so hard to perfect my craft to impress him thinking that the issue was with me, and then the bastard had a heart attack. Left everything to her. What's my mum gonna do with a smithy?!`,
        `I spent a lot of time in the mountains with the Dwarves, and they taught me a thing or two while I was there.`,
      ],
      background: [
        `urchin`,
        `urchin`,
        `urchin`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `noble`,
        `noble`,
        `noble`,
      ],
      weapon: [`a crossbow`, `a longsword`, `a longsword`, `a longsword`, `a dagger`],
      wealth: 2400,
    },
    merchant: {
      dndClassOrigin: [
        `I grew up poor. I learnt to hock stuff off to feed myself.`,
        `Some people just have the gift of the gab- I just have a talent for sales.`,
        `I love gold. Unashamedly, I really do. So what? Selling is an honest living. Sue me.`,
        `I spent my youth selling whatever scraps I could find, never got tired of it.`,
      ],
      background: [
        `urchin`,
        `urchin`,
        `urchin`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `commoner`,
        `noble`,
        `noble`,
        `noble`,
      ],
      weapon: [`a crossbow`, `a longsword`, `a longsword`, `a longsword`, `a dagger`],
      wealth: 2400,
    },
    politician: {
      dndClassOrigin: [
        `I dared to dream that I could change the world, and rise above the others.`,
        `I became furious with the corruption in politics, so I decided to enter the rat-race myself.`,
        `I thought that I could do a better job than the last guy. I was right.`,
      ],
      background: [`commoner`, `commoner`, `commoner`, `commoner`, `noble`, `noble`, `noble`, `criminal`],
      weapon: [`a crossbow`, `a longsword`, `a longsword`, `a longsword`, `a dagger`],
      wealth: 2400,
    },
  },
  bodyParts: {
    // The most notable physical trait of $currentNPC.firstName is that $currentNPC.heshe has ______
    head: {
      hair: [
        `thick, long hair down to their hips`,
        `a mostly shaved head`,
        `a short crewcut`,
        `a pretty short mohawk`,
        `neatly trimmed hair`,
        `wild, unkempt hair`,
        `long curly hair`,
        `short curly hair`,
        `thick straight hair`,
        `thin stringy hair`,
        `small tufts of hair, but not much`,
        `short braided hair`,
        `hair in thick long braids`,
        `thick braids of hair banded with gold`,
        `short, messy hair`,
        `a very short, no-nonsense haircut`,
        `a short, very tailored haircut`,
        `bangs that obscure the eyes`,
        `hair flaked with snowy dandruff`,
        `a hair braid like a thick rope`,
        `hair pulled up in a tight bun`,
        `hair coiled in a top-knot`,
        `greasy looking hair`,
        `rather oily looking hair`,
        `thin whispy hair down to the shoulders`,
        `hair elaborately dressed with ribbons`,
        `hair greased into a ducktail`,
        `locks that flutter to the floor`,
        `incredibly frizzy hair`,
        `hair like straw`,
        `hair that droops down to the cheeks`,
        `matted looking hair`,
        `pigtails`,
        `a very noble haircut`,
        `long messy hair`,
        `hair in a low bun`,
        `has slicked back hair`,
        `braided hair`,
        `a ring of hair`,
        `barely any hair`,
        `long bangs`,
        `a bowl cut`,
        `very bushy hair`,
        `a rat's nest for hair`,
        `a shaved head`,
        `long sideburns`,
        `thin, neatly trimmed sideburns`,
        `thick, tangled hair`,
        `neatly combed hair`,
      ],
      // covers eyes, eyelids, and eyebrows
      eyes: [
        `eyes like a hawk`,
        `quick-witted eyes`,
        `incredibly sharp eyes`,
        `rather dull eyes`,
        `cold eyes`,
        `lifeless looking eyes`,
        `incredibly wide eyes`,
        `slits for eyes`,
        `very droopy eyelids`,
        `rather square shaped eyes`,
        `brilliant eyes`,
        `shifty eyes`,
        `deep crows feet around both eyes`,
        `almond shaped eyes`,
        `beady rat eyes`,
        `a beseeching gaze`,
        `a blazing gaze`,
        `bug-eyes`,
        `bulging eyes`,
        `feline-like eyes`,
        `eyes like a shark`,
        `eyes like liquid pools of color`,
        `sneaky, close-set eyes`,
        `very sunken eyes`,
        `constantly watery eyes`,
        `narrow, wide-set eyes`,
        `moon shaped eyes`,
        `steeply arched brows`,
        `tired looking eyes`,
        `a thick unibrow`,
        `a thin unibrow`,
        `thick, straight eyebrows`,
        `very hairy eyebrows`,
        `thin, curved brows`,
        `outrageously long eyelashes`,
        `very long eyelashes`,
        `eyebrows like checkmarks`,
        `well manicured eyebrows`,
        `eyebrows like caterpillars`,
        `small beady eyes`,
        `strangely bloodshot eyes`,
        `deep-set eyes`,
        `quite owlish eyes`,
        `oval shaped eyes`,
        `slanted eyes`,
        `drawn on eyebrows`,
        `quite sparse eyebrows`,
        `thin, wispy eyebrows`,
        `doe-eyes`,
        `an emotionless gaze`,
        `hollow eyes`,
        `squinty eyes`,
        `twinkling eyes`,
        `wide spaced, sunken eyes`,
        `a black eye`,
        `two black eyes`,
        `enormous eyes`,
        `incredibly tiny eyes`,
      ],
      nose: [
        `a long slender nose`,
        `a rather snout looking nose`,
        `a piggish nose`,
        `a round, bulbous nose`,
        `a short slender nose`,
        `a bird-like nose`,
        `a beaked nose`,
        `a rather bent looking nose`,
        `a boxer's nose`,
        `a broken nose`,
        `a very large nose`,
        `a very small nose`,
        `a quite long nose`,
        `a rather askew nose`,
        `a bovine looking nose`,
        `a broad, flat nose`,
        `a childlike nose`,
        `a chiseled nose`,
        `a cleft nose`,
        `a crooked nose`,
        `a short, curved nose`,
        `a long, curved nose`,
        `a curved nose`,
        `a delicate looking nose`,
        `a dimpled nose`,
        `an elegantly curved nose`,
        `an elegant, round nose`,
        `an enormous nose`,
        `a cat-like nose`,
        `a flaccid looking nose`,
        `a freckled nose`,
        `a fat nose`,
        `a hooked nose`,
        `a thin, hooked nose`,
        `a wide, hooked nose`,
        `an impish nose`,
        `a knobby nose`,
        `a long, lopsided nose`,
        `a narrow, lopsided nose`,
        `a rather lumpy`,
        `a long, lumpy nose`,
        `a round, lumpy nose`,
        `a flat, meaty nose`,
        `an oddly misshapen nose`,
        `a short pinched nose`,
        `a squashed nose`,
        `a wide, wrinkled nose`,
        `a rather noble nose`,
        `a thin, sloped nose`,
        `a broad, sloped nose`,
        `a warty nose`,
        `nose covered in blackheads`,
        `a rather greasy looking nose`,
        `a pockmarked nose`,
      ],
      // covers mouth and cheeks
      mouth: [
        `long thin lips`,
        `thick, full lips`,
        `a permanent smile`,
        `a permanent frown`,
        `a permanent scowl`,
        `very pouty lips`,
        `a permanent look of awe`,
        `tight, pursed lips`,
        `rather dainty lips`,
        `long, thick lips`,
        `narrow, thin lips`,
        `yellowed teeth`,
        `incredibly crooked teeth`,
        `almost rotten looking teeth`,
        `almost no teeth`,
        `a perfect smile`,
        `incredibly white teeth`,
        `perfectly straight teeth`,
        `teeth like headstones`,
        `plump, luscious lips`,
        `very wide lips`,
        `troutlike lips`,
        `dry, cracked lips`,
        `leathery looking lips`,
        `a sagging lower lip`,
        `very full lips`,
        `a fat lip`,
        `a kind smile`,
        `hallowed cheeks`,
        `harsh cheekbones`,
        `sharp cheekbones`,
        `rosy red cheeks`,
        `very high cheekbones`,
        `sunken cheekbones`,
        `soft round cheeks`,
        `plump cheeks`,
        `chubby cheeks`,
        `dimpled cheeks`,
        `large puffy cheeks`,
        `thin ruddy cheeks`,
        `pale, sunken cheeks`,
        `freckled cheeks`,
        `large buck teeth`,
        `teeth like a beaver`,
        `teeth like a horse`,
        `a large gap between the two front teeth`,
        `an underbite`,
        `an overbite`,
      ],
      // covers chin, jaw, and neck
      chin: [
        `a strong, jutting chin`,
        `an angular chin`,
        `a strong cleft chin`,
        `a slight cleft chin`,
        `a double chin`,
        `a large double chin`,
        `a wide beefy chin`,
        `a thin dainty chin`,
        `a rather bony chin`,
        `a wide chin`,
        `a narrow, sunken chin`,
        `a very feminine chin`,
        `a flat chin`,
        `a recessed chin`,
        `an almost non-existant chin`,
        `a misshapen chin`,
        `a noble looking chin`,
        `a flat, pockmarked chin`,
        `a very prominent chin`,
        `a sharp chin`,
        `a quite slender chin`,
        `a well-molded chin`,
        `a square chin`,
        `a soft, rounded chin`,
        `a chiseled jawline`,
        `a well sculpted jaw`,
        `a chin like a shovel`,
        `a delicately rounded jaw`,
        `a caved in chin`,
        `a heavy round jaw`,
        `a jaw narrowed into a pointed little chin`,
        `jowls`,
        `a narrow jawline that arrows into a pointed chin`,
        `a pick-like chin`,
        `a receding chin that makes their nose seem bigger`,
        `a saggy jaw that droops into a turkey neck`,
        `a spade of a chin`,
        `a strong square jaw`,
        `a weak chin`,
        `a prominent jawline`,
        `a smooth, youthful jawline`,
        `a long elegant neck`,
        `a long stocky neck`,
        `a very wide neck`,
        `a quite short, thin neck`,
        `a thin stocky neck`,
        `a narrow neck`,
        `a neck that looks to small for their head`,
        `an incredibly thick neck`,
      ],
      ears: [
        `jug-like ears`,
        `elephant-like ears`,
        `cauliflower ears`,
        `large, protruding ears`,
        `small, protruding ears`,
        `long, thick earlobes`,
        `thin, fat earlobes`,
        `very tiny ears`,
        `small tender ears`,
        `big, floppy ears`,
        `no earlobes`,
        `ears that curl like an exotic shell`,
        `rather pointed ears`,
        `very rounded ears`,
        `very delicate ears`,
        `rather hairy ears`,
      ],
      misc: [
        `a densely pockmarked face`,
        `an incredibly freckly face`,
        `a face covered in freckles`,
        `a well freckled face`,
        `a rather angular face`,
        `a soft rounded face`,
        `a friendly looking face`,
        `a sunken face`,
        `a hollow looking face`,
        `a sharply angled face`,
        `a long, horselike face`,
        `a horseface`,
        `an exceptionally pale face`,
        `a very blocky face`,
        `a baby-face`,
        `a rather blotchy looking face`,
        `a well countoured face`,
        `a flabby face`,
        `a youthful looking face`,
      ],
    },
    torso: {
      descriptions: [
        `a hunched back`,
        `an incredibly large hunch`,
        `very broad shoulders`,
        `incredibly broad shoulders`,
        `quite broad shoulders`,
        `narrow shoulders`,
        `quite rounded shoulders`,
        `terrible posture`,
        `perfect posture`,
        `a large barrel chest`,
        `a barrel chest`,
        `very bony shoulders`,
        `wide set shoulders`,
        `a sunken chest`,
        `a wide ribcage`,
        `a narrow ribcage`,
        `a very narrow waist`,
        `a rather wide waist`,
        `a distended stomach`,
        `rather drooped shoulders`,
        `strong, square shoulders`,
        `broad, powerful shoulders`,
        `very pronounced collar bones`,
        `wide, bony hips`,
        `very narrows hips`,
        `very wide set hips`,
        `a misshapen ribcage`,
      ],
    },
    arms: {
      descriptions: [
        `long, gangly arms`,
        `quite short arms`,
        `arms like a gorilla`,
        `long, spindly fingers`,
        `short, stubby arms`,
        `short, stubby fingers`,
        `child-sized hands`,
        `very hairy forearms`,
        `incredibly veiny arms`,
        `swollen, red knuckles`,
        `quite bony elbows`,
        `fingers like sausages`,
        `heavily calloused hands`,
        `fingernails cut to the quick`,
        `long, brittle fingernails`,
        `colorfully painted nails`,
        `talon-like nails`,
        `nails sharpened to a point`,
        `neatly trimmed fingernails`,
        `small webs between each finger`,
        `long, elegant fingers`,
        `rough, cracked hands`,
        `large swollen knuckles`,
        `impossibly enormous hands`,
        `very muscular hands`,
        `quite muscular arms`,
        `grimy looking fingernails`,
        `yellow-ish fingernails`,
      ],
    },
    legs: {
      descriptions: [
        `more legs than torso`,
        `widely bowed legs`,
        `very notcieable knock knees`,
        `large, knobly knees`,
        `quite stumpy legs`,
        `large, wide feet`,
        `very tiny feet`,
        `feet like a toddler`,
        `feet like a chimp`,
        `almost no kneecaps`,
        `long, monkey like toes`,
        `pale, veiny legs`,
      ],
    },
  },
}

export const raceTraitsData: Record<MajorRace, RaceTrait> = {
  [MajorRace.Dragonborn]: dragonbornTraits,
  [MajorRace.Dwarf]: dwarfTraits,
  [MajorRace.Elf]: elfTraits,
  [MajorRace.Gnome]: gnomeTraits,
  [MajorRace.HalfElf]: halfElfTraits,
  [MajorRace.Halfling]: halflingTraits,
  [MajorRace.HalfOrc]: halfOrcTraits,
  [MajorRace.Human]: humanTraits,
  [MajorRace.Tiefling]: tieflingTraits,
}
