export enum Material {
  Stone = `stone`,
  Wood = `wood`,
  TerraCotta = `terra cotta`,
  Rock = `rock`,
  HewnRock = `hewn rock`,
  Adobe = `adobe`,
  Daub = `daub`,
  Cob = `cob`,
  Plaster = `plaster`,
  Straw = `straw`,
  Brick = `brick`,
  Clay = `clay`,
  Cobblestone = `cobblestone`,
  Limestone = `limestone`,
  Gypsum = `gypsum`,
  Thatch = `thatch`,
  Plank = `plank`,
  Tile = `tile`,
  Shingle = `shingle`,
}
