export enum Weapon {
  Dagger = `dagger`,
  LongSword = `long sword`,
  ShortSword = `short sword`,
  MorningStar = `morning star`,
  Mace = `mace`,
  Axe = `axe`,
  Greataxe = `greataxe`,
  Spear = `spear`,
  Falcheon = `falcheon`,
  BastardSword = `bastard sword`,
  Warhammer = `warhammer`,
  IronCrossbow = `iron crossbow`,
  Claymore = `claymore`,
  Flail = `flail`,
  BroadSword = `broad sword`,
  Pike = `pike`,
  Scimitar = `scimitar`,
  Dart = `dart`,
  Rapier = `rapier`,
  Trident = `trident`,
  Halberd = `halberd`,
  Glaive = `glaive`,
  Lance = `lance`,
  WarPick = `war pick`,
}
