import { randomValue, randomRange } from "../rolls"
import { weightedRandomFetcher } from "../tools/weightedRandomFetcher"
import { locations } from "./locations"
import { encounters } from "./encounters"
import { plothooks } from "../plothook/plothooks"
import { Town } from "../town/town"
import { Biome } from "../../../shared/types"

interface Misc {
  [key: string]: any
}

export const misc: Misc = {
  newspaper: [
    `NPC attempts to become player, ridiculed.`,
    `Underground homunculi fights discovered - homunculi sales increase.`,
    `Wizard house vanishes in the night, locals suspect shenanigans.`,
    `Doppelganger discovered in mayor's place. Townsfolk agree he's better than the old.`,
    `Tiefling, dragonborn, and hobbit visit tavern, local economy booming. (Adventures visited)`,
    `Werewolf suspected to live in town, buy your silver at Jameson's general store!`,
    `Goblins threaten to kill all townsfolk, distracted by 'shiny things'`,
    `Dragon flies over town, local illusionist jailed.`,
    `Lawyer discovered to be vampire, surprising no one.`,
    `Dwarf and human proclaim love, refused wedding ceremony by cleric.`,
    `Dragon rider gives birth to half dragon.`,
    `Centaur's father jailed for bestially.`,
    `Cultists file for rights to be called clerics.`,
    `Forest gnome discovered in wood elf elementary school, been 'stealing our food for years.'`,
    `Portal to elemental plane discovered, hot springs are rejuvenating says discoverer.`,
    `Fey found making old man's shoes, old man to be jailed for slavery.`,
    `Jack steals gold from 'giant in sky' giants pissed.`,
    `Necromancer family man caught trying to raise a family.`,
    `Drunken old ramblings of future discovered to be 90% accurate.`,
    `Dragonborn day-care suspected to be kobold infiltration team.`,
    `Local dungeon deliver finds 'artefact with a demonic presence' leaves it due to lack of modifiers.`,
    `Travelling circus to visit soon.`,
    `Farmer discovers wishing well works.`,
    `Druid makes farm animals talk, town goes vegetarian.`,
    `Druid threatens to awaken plants.`,
    `House pet discovered to be archdruid.`,
    `30 year old half elf sick of 'being treated like a child.'`,
    `Low level adventurers causing trouble in town; seeking rat infested basement to start them on a long quest.`,
    `Lost: Pet invisible stalker, if found return to Wash gust (Wizard). Poster includes a picture of the pet`,
    `Small medium at large; a poster for an escaped gnomish diviner`,
    `Familiars getting too familiar? Please spay or neuter your animal companions.`,
    `'Blurry face of something, angel or demon? Who knows' Do you trust your sight? MADD Magicians Against Drunken Divining.`,
    `St. Cuthbert's school of phrenology and trepanning`,
    `'Beware of doppelgangers!'`,
    `'Local wizard went missing after experimenting with a bag of holding'`,
    `'You will not believe your eyes when you read what this Halfling found in a dungeon!!!'`,
    `'Apprentice sorcerer blew up himself and started a forest fire'`,
    `'Thieves' guild revealed to be just a rumour'`,
    `'Gnome banished from town after drinking 200 potions of inappropriate yodelling'`,
    `'Banshee was still alive hours before she died!'`,
    `'City unsure why the sewer smells.'`,
    `'City guard's raid smithy, find +1 weapons'`,
    `'Goose attacked by aggressive dog, goose refused medical treatment.'`,
    `'Ilitrasee an obstakul for billboards, studee finds.'`,
    `'Group of adventurers mugged by a parrot.'`,
    `'Guard investigation reveals suspicious gold coin to be a copper coin.'`,
    `'Cows lose their jobs as milk prices drop'`,
    `Seeking apprentice cook/tavern staff`,
    `Seeking wizard to remove awaken from my pots and broom.`,
    `Local wizard apprentice blamed for recent flood, discovered to be awakened mouse`,
    `'Local merchant arrested for selling mimics disguised as furniture and appliances, scheme discovered after customer noticed his refrigerator was running.'`,
    `'Rampaging beast destroys slum, townsfolk celebrate new town square.'`,
    `Local instrument shop has massive blowout on Large-sized Lutes, due to a hilarious misunderstanding with local adventurers.`,
    `Help! Help! I'm being held here and made to write these signs!`,
    `Fourth-annual dwarf-throwing competition dissolves into chaos, bloodshed. 'We're looking forward to the fifth year!' says local dwarven merchant.`,
    `Bloodknife the Deathrager, level 20 Barbarian, buys local farm. Interviewed while re-forging a sword into a ploughshare, he said 'My DM doesn't support Epic levels.'`,
    `Strange ill rumours heard from those fleeing from the north. 'Probably nothing,' agrees city council.`,
    `Local wizard's attempt at opening a portal to the Plane of Uncertain Outcomes has succeeded and failed.`,
    `Local church erupts into violence over the usage of non-blunt weaponry among clergy. 'What's next,' cried a local priest, 'Paladins with no alignment restrictions?!'`,
    `Magical cobblers continue to take heavy losses on sales of Boots of Striding and Springing. Demand continues to drop as more editions are released.`,
    `Copyright permit for 11-foot pole denied by local council. 'It IS different!' cried the merchant, as he was escorted from the premises.`,
    `Market share for d12 weapons at an all time low. A local blacksmith was reached for comment, 'Orcs just ain't buyin' no more.'`,
    `A local village has reached a settlement to recompense a magical tailor for injury and losses sustained after the villagers ran him out of town. The elder of the village said, 'We thought t'were one of them parables! Turns out he does sell invisible cloth. We're truly sorry.'`,
    `Dairy farmer to begin offering 'milk for the Khorne flakes'. In an interview, he says 'Well, I began by getting Chaotic Evil cows.'`,
    `Orcs-no-eat insurance! You want not get eat, you pay us gold. Our motto are, 'Your money or you get eat.'`,
    `A local scientist claims 'Humans are slowly being replaced.' He went on to state that, 'These so-called 'variant humans' look exactly like us, and it is nearly impossible to tell if someone you know is one.'`,
    `The town of Westbrynn is under investigation after allegations surfaced that they are offering incentives for higher level creatures to move into the area. Authorities were tipped off after shipments of +5 weapons were intercepted on their way to the town.`,
    `Steampunk genres threaten takeover. Coastal wizards decline to comment`,
    `Lvl 3 familiars unionized! Necromancers at a loss for words`,
    `Gravity subject to change over the next few weeks: alchemists give assurances`,
    `Due to the recent rise in tectonic activity, all elemental mages are advised to avoid using materials near riverbanks and volcanoes`,
    `Dragon scale market plummets as advances in metalwork create stronger materials`,
    `Recent reports confirm health potions to cause loss in bone density. Heavy users of these potions argue that they usually don't live long enough to be effected`,
    `Theoretical alchemists argue the universe was created in a failed transmutation event coined 'The Big Bang'`,
    `'Local gangsters are putting up false notice boards to an excess.'`,
    `Kobold seeks dragon wing for no particular reason.`,
    `Local human scholar in need of parchment urgently.`,
    `Gnome mystic requires escort to deathly swamp.`,
    `Family wedding requires cooks. Will eat any one thing.`,
    `The Order of the Magi requires help in procuring the whereabouts of Magus Ornathuss.`,
    `Animated sword seeks better life; tired of being used in one way relationship.`,
    `Half-elf Baron Faelin Merrybrook found dead at his home. An investigation is still ongoing.`,
    `Finals of the annual tavern brawl to take place tomorrow!`,
    `Doppelganger suffering from identity crisis trying to find purpose in life.`,
    `The Wandering Troupe in town for two days only! Have the minstrels on the run from a bunch of bandits they fleeced and inadvertently involve the characters in their acts.`,
    `Local farmer requires assistance. I am unable to pay you for your troubles I am afraid.`,
    `Dwarf having some trouble removing a ring. The ring is actually a symbiotic ring and has fused with its new owner. It responds well to gluttony, which the dwarf is afflicted by. As the dwarf becomes more charitable, the ring loosens. If anyone wants to wear the ring, it gives 10 temporary hit points at dawn, each day.`,
    `Waresloth seeking help on slow nights.`,
    `Dwarf tossing championship at local tavern, bring your own dwarf.`,
    `Three gnomes in long coat arrested for impersonating human.`,
    `Trigeraian's Used Armour: Eh, it should serve you better than the previous wearer.`,
    `Castle executioner found using illegal muscle enchantments.`,
    `Local elven leader, famously against interracial breeding, found in orc brothel.`,
    `Charngroc's Custom Chimeras: personalized pets for any personality.`,
    `Local oracle revealed to be fraud. 'I just wanted to make a prophet' he says.`,
    `A Capella singing competition finished. Winner was a buomman asking for directions.`,
    `Adventurer teaches blink dog Common. 'Wow. Very language.' comments dog.`,
    `Unidentified kobold mage summons sarrukh. Apocalypse scheduled for 6 PM.`,
    `Evil Lich Necromancer escaped prison. Wanted dead or alive.`,
    `Impersonator discovers his house is a mimic`,
  ],
  patreonCharacters: {
    "Tylien Birchbottom": {
      firstName: `Tylien`,
      lastName: `Birchbottom`,
      /* name: "Tylien Birchbottom", */
      gender: `man`,
      age: `about twenty four`,
      ageYears: 24,
      hasClass: true,
      isThrowaway: false,
      race: `halfling`,
      dndClass: `warlock`,
      height: `rather diminuitive`,
      heightRoll: 34,
      // weightRoll:
      weight: `small and light`,
      idle: [`gently whispering to his petrified mouse`, `writing something in a well-worn notebook`],
      background: `outlander`,
      hairColour: `brown`,
      hairType: `wispy`,
      scar: `lashes on his back that have scarred over`,
      physicalTrait: `lashes on his back that have scarred over`,
      trait: `constantly forgets things, and has to write things down in his journal to be able to remember them properly.`,
      greeting: [`nods at you`, `welcomes you warmly`, `smiles and greets you`, `raises a hand with a wave`],
      dndClassOrigin: `I've been making a decent living hunting game, selling the pelts to the blacksmith for spare change. I'm searching for a cure to my memory decay- every day, I have to write more things down. I need to learn why these things are happening to me... To find out who or whatever the beast of shadows that stalks me is.`,
      backgroundOrigin: `I was kidnapped by a cult at the age of 14. They used me in a ritual to summon an ancient being known as 'the beast of shadows'. Half-way through, guards rescued me. Things got better, and then got a lot worse- I woke speaking tongues, and found myself losing time. As my powers grew, so did my lost time, so I started to keep a journal. Nowadays I can barely remember more than a week into my past now.`,
      owner: `owner`,
      calmTrait: `unintentionally funny`,
      stressTrait: `distant`,
      vocalPattern: `speaks rather quickly`,
      note: `Tylien is Patreon supporter Jasher Drake's PC.`,
    },
    "Galder Fendt": {
      firstName: `Galder`,
      lastName: `Fendt`,
      name: `Galder Fendt`,
      gender: `man`,
      age: `venerable`,
      eyes: `green`,
      ageYears: 84,
      hasClass: true,
      isThrowaway: false,
      race: `human`,
      height: `some five and a half feet`,
      heightRoll: 66,
      weight: `slightly pot-bellied`,
      hairColour: `brilliant white`,
      scar: `a faint cut of a Drow dagger from a long-forgotten skirmish`,
      beard: `a quite respectable beard`,
      physicalTrait: `a respectable beard`,
      trait: `doesn't like to boast, and lets his enemies' perception of an unassuming old man be their downfall.`,
      calmTrait: `quiet`,
      stressTrait: `distant`,
      vocalPattern: `speaks slowly and deliberately`,
      idle: [],
      dndClass: `wizard`,
      background: `sage`,
      dndClassOrigin: ``,
      backgroundOrigin: ``,
      note: `Galder Fendt is the wizard of /u/SomeHairyGuy, a Reddit user who suffered from advanced pelvic RMS. It's his wish that his character, Galder, be used in games around the world. #CreateAgainstCancer`,
    },
    "Brugo Gul'Moth": {
      firstName: `Brugo`,
      lastName: `Gul'Moth`,
      name: `Brugo Gul'Moth`,
      gender: `man`,
      age: `some eighteen years old`,
      eyes: `red`,
      ageYears: 18,
      race: `half-orc`,
      height: `tall, but with a bit of a slouch`,
      heightRoll: 72,
      weight: `muscular`,
      weightRoll: 180,
      hairColour: `shaved bald`,
      hairType: `shiny`,
      scar: `scars everywhere. Not even in cool places. Just everywhere. Hands, legs, arms, chest, back, neck, face, ears, knees, some too close to the groin.`,
      beard: `a quite respectable beard`,
      physicalTrait: `a respectable beard`,
      inventory: `a ritual wooden mask`,
      trait: `Brugo always tries to relate to people through pain, which is often not a great topic for conversation`,
      stressTrait: `begin to hurt himself when under stress. Scratching, hitting, and biting his lip. Never hurts himself with a weapon or to do permanent damage`,
      calmTrait: `stoic and pensive. Brugo likes to observe the world and people around him when he has a peaceful moment.`,
      vocalPattern: `speak in third person. <descriptive>Hello friend! Brugo has happy to see you! Brugo also have bad commonspeak. Is nature. What is "head-you-kay-shun?" Brugo understand your pain. See? This is where Brugo have scar. 12 years old, mountain lion. Brugo last 5 minutes before elders have to rescue. Claw pain was not bad. The true pain was shame. This why Brugo understand. Brugo is friends with you now? Hmm! (Hmm! = Brugo humming+grunting in a way that can be approval, "OK," excitement, or generally any positive affirmation that he cannot find the words to describe). It is his catch-phrase. "Hey Brugo, do you like ale?" "HMM!" "I almost died of hypothermia one time when I was young." "Hmm, Brugo know this pain." "My mother died when I was a baby." "Hmm, Brugo feel this third pain. Please explain third pain with more story, because Brugo have no mother. So Brugo cannot know this pain."</descriptive>`,
      idle: [
        `Brugo stares at his blood-red, wooden ritual mask, which is carved with an incredible number of horrible and frightening scars.`,
      ],
      dndClass: `monk`,
      hasClass: true,
      isThrowaway: false,
      background: `cultist`,
      familyUnit: `Brugo's single father; Brugo has no clue who his mother was.`,
      parentalLineage: `Brugo's father was an orc, and his mother a human. He doesn't know who she was, though.`,
      dndClassOrigin: `Brugo has always liked fight. Brugo discover that being punched is most common pain among outsiders. So Brugo decide that is friendliest profession. Brugo tried other pains but outsiders were lot more scared of them. Brugo get respect for good punches for curious reason.`,
      backgroundOrigin: `Brugo is Son of Gul, Leader of the Cult of Pain. Brugo is of age to be sent on the Pain Quest to discover new methods of pain. Brugo must etch a new scar in ritual mask for each new pain learned.`,
      note: `Brugo is the character of Patreon supporter NaviSaysListen.`,
    },
  },
  town: {
    create(town: Town) {
      return weightedRandomFetcher(town, plothooks, ``, misc.town.type.event)
    },
    type: {
      event(town: Town, arg: any) {
        return arg.type.includes(`event`)
      },
      paper(town: Town, arg: any) {
        return arg.type.includes(`paper`)
      },
    },
  },
  mountain: {
    create(town: Town) {
      let encounter
      let encounterKey
      if (randomRange(1, 100) >= 50) {
        encounterKey = randomValue(misc.mountain.location)
        console.log(encounterKey)
        encounter = locations[encounterKey](town, Biome.Mountain)
        console.log(encounter)
      } else {
        encounterKey = randomValue(misc.mountain.encounters)
        encounter = encounters[encounterKey](town)
      }
      console.log(encounterKey)
      return `${randomValue([`While`, `As`, `After a while, as`])} you ${randomValue([
        `traverse`,
        `trudge along`,
        `travel across`,
        `walk on`,
      ])} the mountain, you see ${randomValue(misc.mountain.landmark)}. You notice ${randomValue(
        misc.mountain.feature
      )}. Up ahead, you see ${encounter}`
    },
    landmark: [
      `a trickle of water flowing down a rock wall`,
      `a small mountain lake of cold, fresh water`,
      `a swiftly flowing small stream`,
      `a natural bridge between two cliff faces`,
      `a narrow gorge with walls close enough to climb between`,
      `a deep gorge with no bottom in sight`,
      `a set of deliberately stacked stones`,
      `a large boulder eroded by the wind into the shape of a near-perfect sphere`,
      `a group of stones arranged in a circle`,
      `a boulder shaped to resemble a face`,
      `a pair of narrow needle-like peaks`,
      `a chimney-like column of rock`,
      `a large boulder split in half like an egg`,
      `a damp rock wall, covered in moss`,
      `the fossilized bones of a great beast visible in a rock wall `,
      `a thicket of hardy mountain shrubs growing atop a boulder`,
      `a copse of scrawny trees`,
      `a gorge where the wind whistles`,
      `a gorge with a near perfect echo`,
      `a rocky shoulder beneath a snowcap`,
    ],
    feature: [
      `a cache of abandoned, decrepit mining equipment`,
      `some old dry bones`,
      `a small fossilized leaf`,
      `evidence of a recent encampment`,
      `an enormous spider web`,
      `an incredible view`,
      `the clatter of rocks falling`,
      `loose stones underfoot`,
      `an unstable rock wall`,
      `a distant sound—a scream, hammers at work, footsteps, or drums`,
      `the name of a previous traveler carved into a boulder`,
      `an ancient rune carved in a rock wall`,
      `a scrawny tree growing with its roots spread over a small boulder`,
      `the distant cry of a beast—an eagle, a goat, a mountain lion, or a wolf`,
      `the wind whips up to a treacherous speed`,
      `snow flurries begin to fall`,
      `the sound of birds chirping`,
      `a flock of birds takes flight`,
      `an old firepit`,
      `several puddles of cold water`,
    ],
    location: [
      `a cavern behind a waterfall`,
      `an entrance to a rocky cave`,
      `a hole under a sheer cliff face`,
      `a dark tunnel leading under the mountain`,
      `a tunnel in a cliff face`,
      `a tunnel leading into an abandoned mine`,
      `a cozy little cabin`,
      `an abandoned cabin`,
      `an abandoned campsite`,
      `a poorly marked grave or tomb`,
      `an active mining camp`,
      `a strategically located watchtower`,
      `an abandoned watchtower`,
      `an enormous bird’s nest`,
      `a shrine`,
      `an isolated monastery`,
      `a remote temple`,
      `an ancient temple`,
      `a ruined monastery`,
      `a small cave in the crook of a rock wall`,
    ],
    cave: [
      `a mountain lion’s den`,
      `lots of bats`,
      `many spider webs`,
      `a troll's stash`,
      `an ogre's lair`,
      `some goblins' hideout`,
      `some abandoned mining equipment`,
      `bare rock`,
      `a potable spring`,
      `unidentifiable remains`,
      `some outlaws’ hideout`,
      `an orc war band`,
      `a hungry ettin`,
      `a band of dwarvish refugees`,
      `a griffon’s nest`,
      `a manticore’s den`,
      `a basilisk’s lair`,
      `a wyvern’s nest`,
      `a clan of stone giants`,
      `a sleeping dragon`,
    ],
    cabinLives: [
      `an owlbear`,
      `an ogre`,
      `a troll`,
      `a mad witch`,
      `a reclusive shapeshifter`,
      `restless ghosts`,
      `an outcast orc`,
      `a strange hermit`,
    ],
    watchtowerLives: [
      `a disciplined military company`,
      `a rowdy mercenary troop`,
      `a band of desperate outlaws`,
      `a handful of dwarves`,
      `a clan of orcs`,
      `a goblin war party`,
      `several harpies`,
      `ghostly warriors`,
    ],
    encounters: [
      `a lost prospector`,
      `a solemn warrior`,
      `an angry wraith`,
      `a malevolent ghost`,
      `some bandits`,
      `a seasoned mountaineer`,
      `a paranoid shapeshifter`,
      `an ancient vampire`,
      `several homeless dwarves`,
      `an eccentric witch`,
      `a contemplative monk`,
      `a mountain lion`,
      `a pair of harpies`,
      `a flock of ravens`,
      `several orc raiders`,
      `a hunting peryton`,
      `a mated pair of manticores`,
      `a trio of monstrous trolls`,
      `a clan of stone giants at rest`,
      `a roc tearing apart some prey`,
    ],
    cabinLived: [
      `a fugitive from justice`,
      `a stubborn miner`,
      `a dwarvish prospector`,
      `a dwarvish war veteran`,
      `a gnomish wizard`,
      `a mystic sage`,
    ],
    camped: [
      `a party of orc scouts`,
      `a goblin raiding party`,
      `some miners or prospectors`,
      `a pair of wandering elves`,
      `some refugees or fugitives`,
      `someone whose purposes are unclear`,
    ],
    miners: [`greedy dwarves`, `ambitious humans`, `tricky goblins`, `industrious kobolds`],
    minersGoal: [
      `copper`,
      `gems`,
      `gold`,
      `iron`,
      `silver`,
      randomValue([`adamantine`, `electrum`, `mithral`, `platinum`]),
    ],
    mineLives: [
      `carrion crawler`,
      `cloaker`,
      `darkmantle`,
      `dwarves`,
      `fungi`,
      `kobolds`,
      `ghosts`,
      `mimics`,
      `myconids`,
      `ogres`,
      `ooze`,
      `orcs`,
      `otyugh`,
      `piercer`,
      `roper`,
      `rust monster`,
      `stirges`,
      `trolls`,
      `umber hulk`,
      `wraiths`,
    ],
    monasteryBuilt: [
      `an order of elementalist monks`,
      `an order of mystics`,
      `an extremely secretive order of monks`,
      `an order of shadow monks`,
      `an order of warrior monks`,
      `an unknown order of monks`,
    ],
    monasteryHonour: [
      `the sun god`,
      `the god of the heavens`,
      `the moon goddess`,
      `the storm god`,
      `the earth mother goddess`,
      `a long-forgotten god`,
    ],
    nestBuilt: [`a giant eagle`, `a giant owl`, `a clan of harpies`, `a griffon`, `a roc`, `a wyvern`],
    watchtowerBuilt: [
      `an expansive empire`,
      `a nearby kingdom`,
      `an occupying army`,
      `elvish warriors from a past age`,
      `a clan of orcs`,
      `a goblin kingdom`,
    ],
    hazards: [
      `a perilous rockslide`,
      `an icy rime across the path or road`,
      `a tumbling boulder`,
      `loose rocks that make for poor footing`,
      `a large boulder blocking the way`,
      `a place where the path has fallen away leaving a narrow ledge on which to walk`,
      `a place where the path or road slopes steeply down toward a cliff edge`,
      `a sudden storm bringing heavy snow`,
    ],
    religionLives: [
      `a congregation of monks`,
      `a group of nuns`,
      `an ancient religious order`,
      `the last of a holy order`,
      `a squad of exiled templars`,
      `a holy congregation`,
      `a rugged looking bunch of refugees`,
      `a single wise guru`,
      `the spirit of a vengeful god`,
      `the spirits of a religion long forgotten`,
    ],
  },
}
