import { randomRange, randomValue } from "../rolls"
import { locations } from "./locations"
import { Biome } from "../../../shared/Biome"
import { encounters } from "./encounters"
import { createTown } from "../town/createTown"
import { rt } from "../tools/randomTemplate"

export interface Mountain {
  readonly feature: string
  readonly landmark: string
  readonly encounter: string
}

export const mountain = {
  create(town = createTown(), base?: Partial<Mountain>): Mountain {
    let encounter: string
    let encounterKey: string

    if (randomRange(1, 100) >= 50) {
      encounterKey = randomValue(mountain.location)
      encounter = locations[encounterKey](town, Biome.Mountain)
    } else {
      encounterKey = randomValue(mountain.encounters)
      encounter = encounters[encounterKey](town)
    }

    return {
      landmark: randomValue(this.landmark),
      feature: randomValue(this.feature),
      encounter,
      ...base,
    }
  },
  readout(mountain: Mountain) {
    const as = [`While`, `As`, `After a while, as`]
    const walk = [`traverse`, `trudge along`, `travel across`, `walk on`]

    return rt`${as} you ${walk} the mountain, you see ${mountain.landmark}. You notice ${mountain.feature}. Up ahead, you see ${mountain.encounter}.`
  },
  landmark: [
    `a trickle of water flowing down a rock wall`,
    `a small mountain lake of cold, fresh water`,
    `a swiftly flowing small stream`,
    `a natural bridge between two cliff faces`,
    `a narrow gorge with walls close enough to climb between`,
    `a deep gorge with no bottom in sight`,
    `a set of deliberately stacked stones`,
    `a large boulder eroded by the wind into the shape of a near-perfect sphere`,
    `a group of stones arranged in a circle`,
    `a boulder shaped to resemble a face`,
    `a pair of narrow needle-like peaks`,
    `a chimney-like column of rock`,
    `a large boulder split in half like an egg`,
    `a damp rock wall, covered in moss`,
    `the fossilized bones of a great beast visible in a rock wall `,
    `a thicket of hardy mountain shrubs growing atop a boulder`,
    `a copse of scrawny trees`,
    `a gorge where the wind whistles`,
    `a gorge with a near perfect echo`,
    `a rocky shoulder beneath a snowcap`,
  ],
  feature: [
    `a cache of abandoned, decrepit mining equipment`,
    `some old dry bones`,
    `a small fossilized leaf`,
    `evidence of a recent encampment`,
    `an enormous spider web`,
    `an incredible view`,
    `the clatter of rocks falling`,
    `loose stones underfoot`,
    `an unstable rock wall`,
    `a distant sound—a scream, hammers at work, footsteps, or drums`,
    `the name of a previous traveler carved into a boulder`,
    `an ancient rune carved in a rock wall`,
    `a scrawny tree growing with its roots spread over a small boulder`,
    `the distant cry of a beast—an eagle, a goat, a mountain lion, or a wolf`,
    `the wind whips up to a treacherous speed`,
    `snow flurries begin to fall`,
    `the sound of birds chirping`,
    `a flock of birds takes flight`,
    `an old firepit`,
    `several puddles of cold water`,
  ],
  location: [
    `a cavern behind a waterfall`,
    `an entrance to a rocky cave`,
    `a hole under a sheer cliff face`,
    `a dark tunnel leading under the mountain`,
    `a tunnel in a cliff face`,
    `a tunnel leading into an abandoned mine`,
    `a cozy little cabin`,
    `an abandoned cabin`,
    `an abandoned campsite`,
    `a poorly marked grave or tomb`,
    `an active mining camp`,
    `a strategically located watchtower`,
    `an abandoned watchtower`,
    `an enormous bird’s nest`,
    `a shrine`,
    `an isolated monastery`,
    `a remote temple`,
    `an ancient temple`,
    `a ruined monastery`,
    `a small cave in the crook of a rock wall`,
  ],
  cave: [
    `a mountain lion’s den`,
    `lots of bats`,
    `many spider webs`,
    `a troll's stash`,
    `an ogre's lair`,
    `some goblins' hideout`,
    `some abandoned mining equipment`,
    `bare rock`,
    `a potable spring`,
    `unidentifiable remains`,
    `some outlaws’ hideout`,
    `an orc war band`,
    `a hungry ettin`,
    `a band of dwarvish refugees`,
    `a griffon’s nest`,
    `a manticore’s den`,
    `a basilisk’s lair`,
    `a wyvern’s nest`,
    `a clan of stone giants`,
    `a sleeping dragon`,
  ],
  cabinLives: [
    `an owlbear`,
    `an ogre`,
    `a troll`,
    `a mad witch`,
    `a reclusive shapeshifter`,
    `restless ghosts`,
    `an outcast orc`,
    `a strange hermit`,
  ],
  watchtowerLives: [
    `a disciplined military company`,
    `a rowdy mercenary troop`,
    `a band of desperate outlaws`,
    `a handful of dwarves`,
    `a clan of orcs`,
    `a goblin war party`,
    `several harpies`,
    `ghostly warriors`,
  ],
  encounters: [
    `a lost prospector`,
    `a solemn warrior`,
    `an angry wraith`,
    `a malevolent ghost`,
    `some bandits`,
    `a seasoned mountaineer`,
    `a paranoid shapeshifter`,
    `an ancient vampire`,
    `several homeless dwarves`,
    `an eccentric witch`,
    `a contemplative monk`,
    `a mountain lion`,
    `a pair of harpies`,
    `a flock of ravens`,
    `several orc raiders`,
    `a hunting peryton`,
    `a mated pair of manticores`,
    `a trio of monstrous trolls`,
    `a clan of stone giants at rest`,
    `a roc tearing apart some prey`,
  ],
  cabinLived: [
    `a fugitive from justice`,
    `a stubborn miner`,
    `a dwarvish prospector`,
    `a dwarvish war veteran`,
    `a gnomish wizard`,
    `a mystic sage`,
  ],
  camped: [
    `a party of orc scouts`,
    `a goblin raiding party`,
    `some miners or prospectors`,
    `a pair of wandering elves`,
    `some refugees or fugitives`,
    `someone whose purposes are unclear`,
  ],
  miners: [`greedy dwarves`, `ambitious humans`, `tricky goblins`, `industrious kobolds`],
  minersGoal: [
    `copper`,
    `gems`,
    `gold`,
    `iron`,
    `silver`,
    randomValue([`adamantine`, `electrum`, `mithral`, `platinum`]),
  ],
  mineLives: [
    `carrion crawler`,
    `cloaker`,
    `darkmantle`,
    `dwarves`,
    `fungi`,
    `kobolds`,
    `ghosts`,
    `mimics`,
    `myconids`,
    `ogres`,
    `ooze`,
    `orcs`,
    `otyugh`,
    `piercer`,
    `roper`,
    `rust monster`,
    `stirges`,
    `trolls`,
    `umber hulk`,
    `wraiths`,
  ],
  monasteryBuilt: [
    `an order of elementalist monks`,
    `an order of mystics`,
    `an extremely secretive order of monks`,
    `an order of shadow monks`,
    `an order of warrior monks`,
    `an unknown order of monks`,
  ],
  monasteryHonour: [
    `the sun god`,
    `the god of the heavens`,
    `the moon goddess`,
    `the storm god`,
    `the earth mother goddess`,
    `a long-forgotten god`,
  ],
  nestBuilt: [`a giant eagle`, `a giant owl`, `a clan of harpies`, `a griffon`, `a roc`, `a wyvern`],
  watchtowerBuilt: [
    `an expansive empire`,
    `a nearby kingdom`,
    `an occupying army`,
    `elvish warriors from a past age`,
    `a clan of orcs`,
    `a goblin kingdom`,
  ],
  hazards: [
    `a perilous rockslide`,
    `an icy rime across the path or road`,
    `a tumbling boulder`,
    `loose rocks that make for poor footing`,
    `a large boulder blocking the way`,
    `a place where the path has fallen away leaving a narrow ledge on which to walk`,
    `a place where the path or road slopes steeply down toward a cliff edge`,
    `a sudden storm bringing heavy snow`,
  ],
  religionLives: [
    `a congregation of monks`,
    `a group of nuns`,
    `an ancient religious order`,
    `the last of a holy order`,
    `a squad of exiled templars`,
    `a holy congregation`,
    `a rugged looking bunch of refugees`,
    `a single wise guru`,
    `the spirit of a vengeful god`,
    `the spirits of a religion long forgotten`,
  ],
}
